### PR TITLE
Update the jsbin link so it has no deprecation warnings

### PR DESCRIPTION
**Pull request by bmac**

### CODE REVIEW

**Comment by wecc** [comment]
Do we want to promote the `JSONAPIAdapter` instead of `RESTAdapter`?

**Comment by igorT** [comment]
Can you set  the html,js flags, as css is not needed

**Comment by bmac** [comment]
@wecc @igorT I have updated this pr to exclude the css page on the jsbin and added a link for the JSONAPIAdapter example.

**Comment by wecc** [comment]
@bmac really nice! getting a deprecation for `shouldReloadAll` in the JSONAPIAdapter one

**Comment by bmac** [comment]
Thanks @wecc the deprecation warning have been fixed.

**Pull request merged**
