### PR TITLE
Unload record instead of dematerialize

### LINKED ISSUE #2780: Record arrays should remove dematerialize records
https://github.com/emberjs/data/pull/2467#issuecomment-72606486

### PR DESCRIPTION
**Pull request by wecc**
- Use store.unloadRecord() in favor of store.dematerializeRecord() (Fixes #2780)
- Deprecate store.dematerializeRecord()

### CODE REVIEW

**Comment by wecc** [comment]
Since `dematerializeRecord()` was never intended for public use, should we just assert instead of deprecate + proxy to `_dematerializeRecord`?

**Comment by sly7-7** [comment]
@wecc Do you think we need a test before merging, to make sure it fixes https://github.com/emberjs/data/pull/2467#issuecomment-72606486 ?

**Comment by wecc** [comment]
@sly7-7 There's already a test to make sure record arrays are updated when records are unloaded: https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/records/unload_test.js#L77

**Comment by sly7-7** [comment]
Sorry, I should have known you already looked at this :smile: 
So, maybe the only missing thing is to update https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/adapter/find_test.js#L124 and using `unload` rather than `dematerialize`

**Comment by wecc** [comment]
@sly7-7 nice catch, test name updated!

**Comment by bmac** [comment]
@sly7-7 I see you added the Needs Discussion label. What concerns do you have with this pr that you think should be discussed?

**Comment by sly7-7** [comment]
@bmac sorry for the delay, I labelled it after @wecc told me there was a discussion about the deprecation vs error on the private _dematarializeRecord method. Since it's merged, I think deprecation is fine for everyone :+1:

**Pull request merged**
