### PR TITLE
[CLEANUP testing]: Remove PhantomJS from testing

### PR DESCRIPTION
**Pull request by alexander-alvarez**
Testing on firefox and chrome by default
Equivalent to https://github.com/ember-cli/ember-cli/pull/7148
And in line with https://github.com/emberjs/rfcs/blob/master/text/0252-browser-support-changes.md

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
tbh -- I'm not sure what the config should be with appveyor, was mostly winging it from what I saw in `ember-cli`

**Comment by rwjblue** [comment]
The failures here are due to `_cacheable` check (that is failing with ember-canary due to an assertion added), which was fixed in #5303.

**Comment by bmac** [comment]
@alexander-alvarez would you mind trying to rebase this pr?

**Comment by alexander-alvarez** [comment]
Rebased

**Comment by bmac** [comment]
Thanks for looking into this @alexander-alvarez. I'm going to close this pr because I think this work has been superseded by https://github.com/emberjs/data/pull/5342.

**Pull request closed without merging**
