### PR TITLE
Avoid errors when ember-cli-shims is not included.

### LINKED ISSUE #4192: ember-cli-shim check errors if no shim is provided
this prevents us from bundling shims with the future ember module.

I suspect something like `this.project.findAddonByName('ember-source')` will be a sufficient check

### PR DESCRIPTION
**Pull request by rwjblue**
Closes #4192.

### CODE REVIEW

**Comment by bmac** [comment]
Restarted travis. Looked like the original issue was unrelated to this code change.

**Comment by rwjblue** [comment]
Ya, but soon we will not be using ember-cli-shims at all (once ember addon follows ember-data's lead and ships its own public modules) so it makes sense to ensure that we don't error when it isn't present...

**Comment by bmac** [comment]
Agreed. I see now my comment was ambiguous. I intended to suggest the reason that travis failed appeared unrelated to this code change.

**Comment by rwjblue** [comment]
Ahh! I see, sorry about the confusion/noise :)

**Pull request merged**
