### PR TITLE
remove unused import

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
This may want to be backported, as it adds several hundred MS to all ember-cli app boots.

**Comment by runspired** [comment]
I'm guessing we forgot to remove this when we stopped doing the globals build? If so, backporting it wouldn't do much as we only removed that in 3.2 beta.

**Comment by runspired** [comment]
Seems we grab babel here though: https://github.com/emberjs/data/pull/5453/files#diff-168726dbe96b3ce427e7fedce31bb0bcL143

Perhaps we forgot to remove this even further back.

**Comment by stefanpenner** [comment]
@runspired ya that backport would be different, it would be to on-demand require the module.

**Pull request merged**
