### PR TITLE
Use the correct modelClass and serializer to extract a polymorphic ty…

### LINKED ISSUE #3547: [Bug] Polymorphic won't work
Hello, I'm trying to work with polymorphic relations, the problem seems to be that it ignores the payload "type" attribute, It will use the payload primary key as modelType instead.

Here is a JsBin: http://emberjs.jsbin.com/wilavu/edit?html,js,output

Let me know what am I doing wrong, if is not a bug I'm really sorry, please close this issue.

Thanks

### PR DESCRIPTION
**Pull request by bmac**
…pe when normalizing async relationships.

Closes #3547

### CODE REVIEW

**Comment by bmac** [comment]
@marcemira I believe this fixes https://github.com/emberjs/data/issues/3547.


@igorT and @wecc can you review?

**Comment by wecc** [comment]
LGTM but we should implement the same thing [here](https://github.com/bmac/data/blob/bug-3547/packages/ember-data/lib/serializers/rest-serializer.js#L142-L160) or it will only work for singular object root keys.

Maybe a private helper method wrapping this would be nice?

**Comment by marcemira** [comment]
:+1:  great! Thank you guys :grin:

**Comment by jrhe** [comment]
I can confirm that this fixes #3547 but only for singular keys. Needs the fix @wecc mentioned.

**Comment by bmac** [comment]
@wecc, I have updated this pr. Do you mind reviewing it again?

**Comment by wecc** [comment]
I would like to DRY this up a bit and move the duplicate code to a helper but we can definitely do that later.

:shipit:

**Pull request merged**
