### PR TITLE
handle DNS resolution failure in chrome as TimeoutError

### PR DESCRIPTION
**Pull request by BryanCrotaz**
As referenced in #5486

### CODE REVIEW

**Comment by BryanCrotaz** [comment]
Don't know how to go about writing tests for this

**Comment by BryanCrotaz** [comment]
Not sure this is correct. Will close and reopen a new PR later

**Comment by runspired** [comment]
@BryanCrotaz I think this answer has enough info for us to get it right: https://stackoverflow.com/questions/3825581/does-an-http-status-code-of-0-have-any-meaning

**Comment by BryanCrotaz** [comment]
unfortunately I couldn't find a way to differentiate between an DNS resolution error and all cross domain errors. Cross domain 404 or 500 comes back as status=0 :(

**Comment by runspired** [comment]
:'( maybe we need to add a "generic connection error"

**Comment by BryanCrotaz** [comment]
can we spot from the url and document.location that this is a cross domain request and give a different error?

**Pull request closed without merging**
