### PR TITLE
Add queryRecord method to the RESTAdapter

### PR DESCRIPTION
**Pull request by thaume**
I just added the queryRecord to the RESTAdapter, it still needs more tests (coming soon)

### CODE REVIEW

**Comment by bmac** [comment]
Awesome. Thanks for getting to this @thaume

**Comment by wecc** [comment]
@thaume what's the status of this? anything I can do to help?

**Comment by thaume** [comment]
@wecc I just need to write a couple more tests, I'll try to do that today so that we can merge it before I leave for 2 weeks away from keyboard

**Comment by thaume** [comment]
@wecc @bmac I just added more tests, do you think we need more ? I feel like there are already many integration tests in the store/query-record-test file

**Comment by bmac** [comment]
@thaume What happens of `posts` is an array instead of a single object?

**Comment by thaume** [comment]
@bmac  It picks the record at index 0, but it still saves all the other records in the store. Do you think this is the intended result ? :)

**Comment by bmac** [comment]
I do. The tests look good. Can you squash these commits and prefix the commit with [BUGFIX release]?

**Comment by thaume** [comment]
@bmac there you go

**Comment by bmac** [comment]
Thanks

**Comment by wecc** [comment]
:tada:

**Comment by thaume** [comment]
cool :)

**Pull request merged**
