### PR TITLE
Split Relationship Tests into Separate Files

### PR DESCRIPTION
**Pull request by seanpdoyle**
Multiple `Qunit.modules` lacking shared setup should live in separate
files.

### CODE REVIEW

**Comment by igorT** [comment]
Can you please in the future make changes that move code and also change it, into multiple commits. It's super hard to review `Merge nested / adjacent run(function() {}) blocks` because there is no diff

**Comment by igorT** [comment]
Do you remember how many there were?

**Comment by seanpdoyle** [comment]
@igorT sure thing. Hold off on merging this and I'll re-do the work in separate braches

**Comment by seanpdoyle** [comment]
@igorT reworked this to ignore adjacent `run` calls

**Pull request merged**
