### PR TITLE
Run windows tests on azure

### PR DESCRIPTION
**Pull request by igorT**

### CODE REVIEW

**Comment by runspired** [comment]
We should have both a mac and a windows set of jobs, yes? Or do we just want to run on windows? cc @rwjblue

**Comment by igorT** [comment]
This is still a WIP, currently appyveyor runs 3/4 tests on windows, so running those

**Comment by igorT** [comment]
ready for review @runspired

**Comment by igorT** [comment]
given that we develop on macs, I think we should run most of the tests on OS X

**Comment by runspired** [comment]
So stoked to kill appveyor

**Pull request merged**
