### PR TITLE
[Bugfix release] Remove some usages of enumerable utils that made it …

### PR DESCRIPTION
**Pull request by bmac**
…into the release branch

### CODE REVIEW

**Comment by stefanpenner** [comment]
Are these also addresses in master? Basically are they using the native es5 in master?

**Comment by bmac** [comment]
Yes these are already using native es5 methods on master.

https://github.com/emberjs/data/blob/master/packages/activemodel-adapter/lib/system/active-model-serializer.js#L279

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-api-serializer.js#L39

**Comment by stefanpenner** [comment]
Perfect. Just wanted to make sure I didn't miss them

**Comment by wecc** [comment]
:+1:

**Pull request merged**
