### PR TITLE
[BUGFIX beta] Move ember-inflector to an explicit dependency for the …

### PR DESCRIPTION
**Pull request by bmac**
…Ember CLI build

### CODE REVIEW

**Comment by fivetanley** [comment]
This will cause it not to load. Ember CLI won't look at nested dependencies.

**Comment by fivetanley** [comment]
Err, it's already in peerDependencies, do we need it as a dependency?

**Comment by rwjblue** [comment]
> This will cause it not to load. Ember CLI won't look at nested dependencies.

Not sure what you mean. ember-cli definitely supports nested dependencies. There are some issues with nested deps that use `included`, but that isn't the case here ([based in this](https://github.com/stefanpenner/ember-inflector/blob/master/index.js)).

**Comment by rwjblue** [comment]
`peerDependencies` allows the application to bring its own also, but if ember-data does actually depend on ember-inflector why would we not want it as a dep?

**Comment by bmac** [comment]
@fivetanley this may not be the correct fix. 
I just created [this repo](https://github.com/bmac/test-2-3-0-beta) in an attempt to debug http://discuss.emberjs.com/t/jsonapiadapter-not-recognized-findall-is-not-a-function/9307 and I was seeing this error. 

screen shot 2015-12-21 at 10 28 55 am


Previously I had been using [this repo](https://github.com/bmac/active-model-adapter-ember-cli-2-beta-issue) to test the 2.3 beta but I didn't notice until now that it explicitly included the [ember-inflector dependency](https://github.com/bmac/active-model-adapter-ember-cli-2-beta-issue/blob/master/package.json#L42).

**Comment by fivetanley** [comment]
> ember-cli definitely supports nested dependencies

when I was starting to look at addonifying in the early part of the year, it sounded like this was not the case. I'm glad it does account for this now. Using it as a `dependency` seems fine then.

@bmac are you using npm 2 or 3? 2 warns, 3 fails install if the peerDep isn't met

**Comment by bmac** [comment]
Looks like I'm currently using npm `2.14.2`.

**Comment by fivetanley** [comment]
Doing it as a dependency, since it's possible (my bad, i thought it wasn't), seems better so we won't get tickets like this. Not sure what the advantage of using a peerDependency would be if nested dependencies work.

**Comment by rwjblue** [comment]
> when I was starting to look at addonifying in the early part of the year, it sounded like this was not the case.

Ya, you are totally correct.  It only landed a bit before 1.13.0 of ember-cli, so it hasn't been around too long.

**Pull request merged**
