### PR TITLE
Deprecate store.find(type) and store.find(type, query)

### LINKED ISSUE #2607: Deprecate `store.find` acting as findQuery/findAll to use store.findAll and findQuery
Currently, store.find supports several function signatures:

`store.find('type')` => `store.findAll`
`store.find('type', {queryParam: 'hi'})` => `store.findQuery`
`store.find('type', '1')` => `store.find`

We should only support the last version of this form for 1.0, and deprecate until then.

### PR DESCRIPTION
**Pull request by wecc**
Should fix #2607

### CODE REVIEW

**Comment by bmac** [comment]
This is going to be a big change. We should also have a note about this in the change log and be ready to update the guides in the https://github.com/emberjs/website repo.

**Comment by wecc** [comment]
I've added breaking changes the CHANGELOG and created a PR to update the guides at https://github.com/emberjs/website/pull/1966

**Comment by pixelhandler** [comment]
I'm curious how the default model hook in the route will behave, will it call find, findAll, or findQuery. Will here be branching based on the params?

**Comment by rwjblue** [comment]
@pixelhandler - Wonderful question!

**Comment by wecc** [comment]
@pixelhandler @rwjblue From my understanding the default model hook only loads data from the store when we have a model and an id, in which case the current call to find() is the right one.

**Comment by wecc** [comment]
Relevant: https://github.com/emberjs/rfcs/pull/27

**Pull request closed without merging**
