### PR TITLE
[FEATURE ds-adapter-jqxhr] Enable adapter to have access to full jqXHR in response #4404

### PR DESCRIPTION
**Pull request by eshtadc**
I couldn't find an existing test that utilized the "ajax" method to ensure that the response is properly handled there as well.

### CODE REVIEW

**Comment by tchak** [comment]
May I ask what is the use case to have access to `xhr` object? Adapter hooks are designed explicitly to NOT expose `xhr` object. `xhr` is an implementation detail and in this case it's not even real `xhr`, but the `jQuery` wrapper that you trying to expose. It means `jQuery` becoming our public API. This is something we want to avoid because sometime in the feature we going to have to switch to `fetch` API and there will be no `xhr` object.

We tried to make sure we exposed all the useful information from `xhr` object. What's missing?

**Comment by lkhaas** [comment]
Yes - I had commented in the issue #4404 that it did appear that jqXHR wasn't being exposed intentionally.  Our specific use case is to be able to validate a header that our server adds as part of our authorization handshake.  The header added is generated from some information from the request as well as the responseText (response body).  We store a few properties on the jqXHR itself, but I could get access to them during the beforeSend and then store them for validation later in the handleResponse function.  This still leaves me without the response body, however.  

I could also rewrite this PR to only add the response body (`responseText`) property in order to prevent the jQuery dependency.  Although the jQXHR is in itself just an abstraction as you point out.  It does expose all functionality of the underlying XMLHttpRequest object.  

What if ember-data still exposed the jqXHR but with the notion that it is the XMLHttpRequest object.  Then if one was to use something other than jQuery, they could still provide access to the XMLHttpRequest object.  The expectation could be that the base XMLHttpRequest is the only portion part of the ember-data api and things that jQuery adds (like promises, etc.) are just bonus?  Otherwise I feel like the ember-data will just keep adding individual values from the XMLHttpRequest object in a piecemeal fashion as needed by developers.

**Comment by fivetanley** [comment]
> It means jQuery becoming our public API. 

Not necessarily. We have had plans to roll jQuery based stuff into its own adapter once ember-ajax nears completion. Since we're just sticking it on an options hash, we could document it as "jquery specific." This does not mean we have to support it on adapters that don't use jQuery.

I think it is very important for developers to have escape hatches, whether that's the raw XHR object or a jqXHR object. For instance, if your app needs to consume an API like Github's where the metadata is *very* header based, you can't do it currently without hacks or custom `$.ajax` rolling. You used to be able to access them and I remember working with a colleague at Instructure to expose jqXHRs pre-1.13.

I agree that most of these types of decisions should be available in some sort of raw form (e.g. we should be exposing headers), but it's important for users to have the escape hatch. Putting it on the options hash allows us to either deprecate or remove support in one isolated instance. It does not mean that jQuery is the new public facing API.

**Comment by bmac** [comment]
Sorry for the slow response @eshtadc. I've been busy with work work.

We talked about this pr again in the last meeting and @igorT's concern with exposing a "jquery specific" escape hatch is because of Fastboot the same app may be expected to run in a jQuery and a non jQuery environment.

At this point I think the best option would be to expose some non-jquery specific wrapper for the XMLHttpRequest  object, or the raw XMLHttpRequest itself.

@tomdale Does fastboot expose request/response objects to the Ember app?

**Comment by tchak** [comment]
@bmac `fastboot` is relying on `najax` which is an implementation `of `$.ajax` in node. It will expose a sort of `jqXHR` object.

**Comment by eshtadc** [comment]
@bmac Yes - work work... it is the bane of my involvement in all sorts of things ;-)

I don't have any real understanding of fastboot yet.  I can definitely update this pr to be 1) re-rolled; 2) more generic to xhr object, but I'm at a loss of how to take fastboot into account.

**Comment by gnanavelum** [comment]
is there a conclusion this?

I have a same use case to access the jqXhr on both success and false callbacks.

**Comment by topaxi** [comment]
@gnanavelum there seems to be a migration away from jQuery, I think there needs to be a new solution to this as exposing `jqXHR` would block the migration.

**Comment by runspired** [comment]
@eshtadc I am sad this languished so long :( We do want to improve the request layer, and are working on a concept that should hopefully resolve a lot of these issues around not enough information being exposed.

However, this approach isn't the direction we want to take both because we want to ensure Fastboot support and because we want to migrate away from jQuery and thus need to avoid leaking it.

**Pull request closed without merging**
