### PR TITLE
[BUGFIX] Clarifying error message for polymorphic types

### PR DESCRIPTION
**Pull request by pete-the-pete**
fix for #4633

### CODE REVIEW

**Comment by jmar910** [comment]
@pete-the-pete spent the afternoon working on this and realized you beat me to the punch. It looks like you need to update some more tests with the updated assertion. Feel free to use my work here https://github.com/jmar910/data/commit/97d403fcf806ca32d743118b14c318f7f5d86dd0

**Comment by pete-the-pete** [comment]
awesome, thanks! sorry for the duplicated effort.

**Comment by jmar910** [comment]
no worries at all!

**Comment by runspired** [comment]
Thanks so much @pete-the-pete @jmar910

**Pull request merged**
