### PR TITLE
[wip] run tests on saucelabs

### PR DESCRIPTION
**Pull request by fivetanley**

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Excited to see you trying `ember-cli-sauce`. Ping me if you need any help :-)

**Comment by igorT** [comment]
@fivetanley this still active?

**Comment by fivetanley** [comment]
yes

**Comment by bmac** [comment]
@fivetanley do you have time to drive this pr to completion or has it gone stale?

**Comment by bmac** [comment]
ping @fivetanley do you have time to give this pr some love?

**Comment by bmac** [comment]
@fivetanley what is the status on this pr?

**Comment by bmac** [comment]
I'm going to close this issue since there hasn't been any response in a while. Feel free to reopen if there is an update.

**Pull request closed without merging**
