### PR TITLE
[BUGFIX] JSONAPI serializer not respecting 'attrs' hash

### PR DESCRIPTION
**Pull request by weinberg**
Fix for [3810](https://github.com/emberjs/data/issues/3810).

This applies `normalizeUsingDeclaredMapping` to both the `attributes` and `relationships` of the resource hash in `normalize`.

There is another bug which exists for multi-word property names and the `attrs` hash.  I didn't want to try to fix that at the same time - I'll file a separate issue for that.

### CODE REVIEW

**Comment by bmac** [comment]
This looks great @weinberg. Do you mind squashing this pr into 1 commit and prefixing it with `[BUGFIX beta]`? if you need help with the git commands to make that happen let me know.

**Comment by weinberg** [comment]
Hi @bmac - I could use some help with the git commands to do that. Thanks!

**Comment by bmac** [comment]
First crate a new branch to save your current work. Lets call it `pr-3845`.
`git checkout -b pr-3845`

Then checkout master again.
`git checkout master`


And lets reset master to a commit that exists in the upstream Ember Data repo. (This will prevent the merge commits from showing up in the new branch we are going to create.)

`git reset --hard 92c36f4ba0665a689cdcfc5e4b46e9d63bca8cb4`

Now lets create a new branch. Starting at this point in the Ember Data repo's history. This branch will be called `pr-2845-squash`.

`git checkout -b pr-3845-squash`

Now we want to merge the contents of the `pr-3845` branch into the new `pr-3845-squash` branch. We are going to use the `--squash` flag to tell git to squash everything into 1 commit.

`git merge --squash pr-3845`

If you do a `git status` you should see 2 unmerged files. Now we can write out the commit message.

git commit -m "[BUGFIX beta] JSONAPI serializer not respecting 'attrs' hash"

Finally `git push` to push the branch up to your repo on github.

Its possible to push this branch up to your `master` branch on github so it will automatically update this pr by doing. `git push -f origin pr-3845-squash:master` (that command overrides the `master` banch on `origin` (aka your github repo) with the `pr-2845-squash` branch). But it would also be fine to open a new pr from the new `pr-2845-squash` branch. (It is generally considered a good practice to open prs from a branch other then master).

Let me know if you need any more help.

**Comment by weinberg** [comment]
Thanks for the help @bmac! I have opened a new PR with the squashed commits. I'll close this one.

**Pull request closed without merging**
