### PR TITLE
use the esperanto module transpiler

### PR DESCRIPTION
**Pull request by fivetanley**
don't merge til the next release; this breaks ie8

### CODE REVIEW

**Comment by stefanpenner** [comment]
why does this break IE8?

**Comment by fivetanley** [comment]
https://github.com/esperantojs/esperanto/wiki/Converting-a-single-module#options

> _evilES3SafeReExports - will cause re-exported bindings to be done with direct property assignment rather than Object.defineProperty(). In most cases, the resulting behaviour will be no different, but it could result in undefined bindings in cases of cyclical dependencies, and values are fixed at the time of re-export rather than live

we don't use that option

**Comment by stefanpenner** [comment]
> we don't use that option

why not? 

I am confused why ember uses esperanto while supporting IE8 but this does not

**Comment by fivetanley** [comment]
we won't be supporting ie8 as of the next release

**Comment by stefanpenner** [comment]
> we won't be supporting ie8 as of the next release

ah, so no reason other then we are dropping support anyways

**Comment by fivetanley** [comment]
yeah, apparently @igort has something that requires cyclical deps?

**Comment by igorT** [comment]
@fivetanley I could refactor but you said to just wait 10 min :)

**Comment by stefanpenner** [comment]
Esperanto is no more

**Pull request closed without merging**
