### PR TITLE
Update "blueprint-test-helpers" and "ember-cli"

### PR DESCRIPTION
**Pull request by Turbo87**
This PR updates the "ember-cli-blueprint-test-helpers" dependency to v0.10.1 which fixes the `throws` assertion. This however makes another bug in `ember-cli@2.3.x` visible, which is fixed by updating to `ember-cli@2.4.1`

This should resolve some of the issues experienced in https://github.com/emberjs/data/pull/4023

/cc @pangratz @trabus

### CODE REVIEW

**Comment by Turbo87** [comment]
oh well, looks like this is causing even more unrelated issues

**Comment by Turbo87** [comment]
@pangratz this seems to work fine now. I'd suggest merging this PR and then rebasing #4023 on top of it.

**Comment by pangratz** [comment]
@Turbo87 thanks for the heads up. Can you squash?

**Comment by pangratz** [comment]
Thanks for the work on this @Turbo87

**Pull request merged**
