### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by igorT**

### CODE REVIEW

**Comment by runspired** [comment]
Can we setup IE and Windows jobs on azure as well to kill off our appveyor usage?

**Comment by igorT** [comment]
@runspired Given how slow Travis is, don't think there is a need for waiting, as if the extra tests fail(which they shouldn't) we can ignore them for now, and we don't publish beta/release versions often enough for that to block this PR IMO

**Comment by igorT** [comment]
@runspired yeah, hopefully, I'll look into how appveyor is setup sometime later

**Comment by igorT** [comment]
I'll look into not running the external partner tests and in progress features as a followup task

**Comment by runspired** [comment]
> Given how slow Travis is, don't think there is a need for waiting, as if the extra tests fail(which they shouldn't) we can ignore them for now

This is a separate point from that in my review which I thought you were going to include a fix for here in which we fail fast if `lint` and `basic tests` fail?

**Comment by igorT** [comment]
Investigating couple different solutions for that, will come up in a follow on PR

**Pull request merged**
