### PR TITLE
Rename Model.rollback() to model.rollbackAttributes()

### PR DESCRIPTION
**Pull request by HeroicEric**
Fixes https://github.com/emberjs/data/issues/3273

- renames `Model.rollback()` to `Model.rollbackAttributes()`.
- adds deprecation to `Model.rollback()`
- renames `InternalModel.rollback()` to `InternalModel.rollbackAttributes()`

### CODE REVIEW

**Comment by igorT** [comment]
@HeroicEric Thanks! InternalModel sounds good as well if you want

**Comment by HeroicEric** [comment]
added renaming `InternalModel.rollback()` to `InternalModel.rollbackAttributes()`

**Comment by wecc** [comment]
LGTM

**Comment by bmac** [comment]
Looks good. @HeroicEric do you mind squashing these commits?

**Pull request merged**
