### PR TITLE
Revert "[CHORE] auto publish alpha versions"

### PR DESCRIPTION
**Pull request by runspired**
Reverts #7436 cc @spham92 

See this failure: https://github.com/emberjs/data/commit/2feb0c1a9f2e54fbbcdeaba0d62468a4a5dadebb

I manually ran `npm view ember-data versions --json` and see the following

<details>
<summary>Output</summary>
```json
[
  "1.0.0-beta.10",
  "1.0.0-beta.11",
  "1.0.0-beta.12",
  "1.0.0-beta.14",
  "1.0.0-beta.14.1",
  "1.0.0-beta.15",
  "1.0.0-beta.16",
  "1.0.0-beta.16.1",
  "1.0.0-beta.17",
  "1.0.0-beta.18",
  "1.0.0-beta.19",
  "1.0.0-beta.19.1",
  "1.0.0-beta.19.2",
  "1.13.0",
  "1.13.1",
  "1.13.2",
  "1.13.3",
  "1.13.4",
  "1.13.5",
  "1.13.6",
  "1.13.7",
  "1.13.8",
  "1.13.9",
  "1.13.10",
  "1.13.11",
  "1.13.12",
  "1.13.13",
  "1.13.14",
  "1.13.15",
  "1.13.16",
  "2.0.0-beta.1",
  "2.0.0-beta.2",
  "2.0.0",
  "2.0.1",
  "2.1.0-beta.1",
  "2.1.0-beta.2",
  "2.1.0-beta.3",
  "2.1.0-beta.4",
  "2.1.0-beta.5",
  "2.1.0",
  "2.2.0-beta.1",
  "2.2.0-beta.2",
  "2.2.0-beta.3",
  "2.2.0-beta.4",
  "2.2.0",
  "2.2.1",
  "2.3.0-beta.1",
  "2.3.0-beta.2",
  "2.3.0-beta.3",
  "2.3.0-beta.4",
  "2.3.0-beta.5",
  "2.3.0",
  "2.3.1",
  "2.3.2",
  "2.3.3",
  "2.4.0-beta.1",
  "2.4.0-beta.2",
  "2.4.0-beta.3",
  "2.4.0",
  "2.4.1",
  "2.4.2",
  "2.4.3",
  "2.5.0-beta.1",
  "2.5.0-beta.2",
  "2.5.0-beta.3",
  "2.5.0-beta.4",
  "2.5.0",
  "2.5.1",
  "2.5.2",
  "2.5.3",
  "2.5.4",
  "2.5.5",
  "2.6.0-beta.1",
  "2.6.0-beta.2",
  "2.6.0-beta.3",
  "2.6.0-beta.4",
  "2.6.0",
  "2.6.1",
  "2.6.2",
  "2.7.0-beta.1",
  "2.7.0-beta.2",
  "2.7.0-beta.3",
  "2.7.0",
  "2.8.0-beta.1",
  "2.8.0-beta.2",
  "2.8.0-beta.3",
  "2.8.0",
  "2.8.1",
  "2.9.0-beta.1",
  "2.9.0-beta.2",
  "2.9.0-beta.3",
  "2.9.0-beta.4",
  "2.9.0",
  "2.10.0-beta.1",
  "2.10.0-beta.2",
  "2.10.0-beta.3",
  "2.10.0",
  "2.11.0-beta.1",
  "2.11.0",
  "2.11.1",
  "2.11.2",
  "2.11.3",
  "2.12.0-beta.1",
  "2.12.0-beta.2",
  "2.12.0-beta.3",
  "2.12.0-beta.4",
  "2.12.0",
  "2.12.1",
  "2.12.2",
  "2.13.0-beta.1",
  "2.13.0-beta.2",
  "2.13.0-beta.3",
  "2.13.0-beta.4",
  "2.13.0",
  "2.13.1",
  "2.13.2",
  "2.14.0-beta.1",
  "2.14.0-beta.2",
  "2.14.0-beta.3",
  "2.14.0",
  "2.14.1",
  "2.14.2",
  "2.14.3",
  "2.14.4",
  "2.14.5",
  "2.14.6",
  "2.14.7",
  "2.14.8",
  "2.14.9",
  "2.14.10",
  "2.14.11",
  "2.15.0-beta.1",
  "2.15.0-beta.2",
  "2.15.0-beta.3",
  "2.15.0-beta.4",
  "2.15.0",
  "2.15.1",
  "2.15.2",
  "2.15.3",
  "2.15.4",
  "2.16.0-beta.1",
  "2.16.0",
  "2.16.1",
  "2.16.2",
  "2.16.3",
  "2.16.4",
  "2.17.0-beta.1",
  "2.17.0-beta.2",
  "2.17.0",
  "2.17.1",
  "2.18.0-beta.1",
  "2.18.0",
  "2.18.1",
  "2.18.2",
  "2.18.3",
  "2.18.4",
  "2.18.5",
  "3.0.0-beta.1",
  "3.0.0",
  "3.0.1",
  "3.0.2",
  "3.0.4",
  "3.1.0-beta.1",
  "3.1.0-beta.2",
  "3.1.0",
  "3.1.1",
  "3.1.2",
  "3.2.0-beta.1",
  "3.2.0-beta.2",
  "3.2.0-beta.3",
  "3.2.0-beta.4",
  "3.2.0",
  "3.2.1",
  "3.2.2",
  "3.3.0-beta.1",
  "3.3.0-canary",
  "3.3.0",
  "3.3.1",
  "3.3.2",
  "3.4.0-beta.1",
  "3.4.0-beta.2",
  "3.4.0-beta.3",
  "3.4.0-beta.4",
  "3.4.0",
  "3.4.1",
  "3.4.2",
  "3.4.3",
  "3.4.4",
  "3.5.0-beta.1",
  "3.5.0-beta.2",
  "3.5.0-beta.3",
  "3.5.0",
  "3.5.1",
  "3.5.2",
  "3.6.0-beta.1",
  "3.6.0",
  "3.7.0",
  "3.8.0",
  "3.8.1",
  "3.9.0-beta.1",
  "3.9.0",
  "3.9.1",
  "3.9.2",
  "3.9.3",
  "3.10.0-beta.1",
  "3.10.0",
  "3.11.0-beta.1",
  "3.11.0-beta.2",
  "3.11.0",
  "3.11.1-canary.0",
  "3.11.1",
  "3.11.2",
  "3.11.3",
  "3.11.4",
  "3.11.5",
  "3.12.0-beta.0",
  "3.12.0-canary.0",
  "3.12.0-canary.1",
  "3.12.0-canary.2",
  "3.12.0",
  "3.12.1",
  "3.12.2",
  "3.12.3",
  "3.12.4",
  "3.12.5",
  "3.12.6",
  "3.13.0-beta.0",
  "3.13.0-beta.1",
  "3.13.0-beta.2",
  "3.13.0-canary.0",
  "3.13.0",
  "3.13.1",
  "3.13.2",
  "3.13.3-alpha.0",
  "3.13.3",
  "3.14.0-alpha.0",
  "3.14.0-alpha.1",
  "3.14.0-alpha.2",
  "3.14.0-alpha.3",
  "3.14.0-alpha.4",
  "3.14.0-beta.0",
  "3.14.0-beta.2",
  "3.14.0",
  "3.14.1",
  "3.15.0-alpha.0",
  "3.15.0-alpha.1",
  "3.15.0-beta.0",
  "3.15.0",
  "3.15.1",
  "3.16.0-alpha.0",
  "3.16.0-alpha.2",
  "3.16.0-alpha.3",
  "3.16.0-beta.0",
  "3.16.0-beta.1",
  "3.16.0",
  "3.16.2",
  "3.16.3",
  "3.16.4",
  "3.16.5",
  "3.16.6",
  "3.16.7",
  "3.16.8",
  "3.16.9",
  "3.17.0-alpha.0",
  "3.17.0-beta.0",
  "3.17.0",
  "3.17.1",
  "3.18.0-alpha.0",
  "3.18.0-beta.0",
  "3.18.0",
  "3.19.0-alpha.0",
  "3.19.0-beta.0",
  "3.19.0",
  "3.20.0-alpha.0",
  "3.20.0-beta.0",
  "3.20.0",
  "3.20.1",
  "3.20.2",
  "3.20.3",
  "3.20.4",
  "3.20.5",
  "3.21.0-alpha.0",
  "3.21.0-beta.0",
  "3.21.0-beta.1",
  "3.21.0",
  "3.21.1",
  "3.21.2",
  "3.22.0-alpha.0",
  "3.22.0-alpha.1",
  "3.22.0-beta.0",
  "3.22.0-beta.1",
  "3.22.0-beta.2",
  "3.22.0-beta.3",
  "3.22.0",
  "3.22.1",
  "3.23.0-alpha.0",
  "3.23.0-beta.0",
  "3.23.0",
  "3.24.0-alpha.0",
  "3.24.0-alpha.1",
  "3.24.0-beta.0",
  "3.24.0",
  "3.24.1",
  "3.24.2",
  "3.25.0-alpha.0",
  "3.25.0-beta.0",
  "3.25.0",
  "3.26.0-alpha.0",
  "3.26.0-beta.0",
  "3.26.0",
  "3.27.0-alpha.0",
  "3.27.0-beta.0",
  "3.28.0-alpha.0"
]
```
</details>

I think there are likely two bugs to fix:

1) I notice that this script starts from the end of the list to determine the last alpha. `3.28.0-alpha.0` was indeed published 23 days ago and should have been what it used for determining the next alpha, however it seems to have picked up on the `3.27` tag instead.

2) I think there is a second issue with the check is that we always will find a lastAlpha, so incrementing if there is not yet a published alpha for the current release cycle will not work as expected, we would never hit the first branch here and always hit the second.

```js
if (lastRelease && !lastAlpha) {
    return console.log(semver.inc(lastRelease, 'preminor', 'alpha'));
  } else if (lastAlpha) {
    return console.log(semver.inc(lastAlpha, 'prerelease', 'alpha'));
  } else {
    throw Error('Could not determine next version because no recent release or alpha version');
  }
```

### CODE REVIEW

**Comment by spham92** [comment]
Hi @runspired, thanks for identifying the issues. Let me get these fixed

> The tag that it generated was not published to npm. This indicates a failure in this job somewhere that should have been reported but wasn't.

Most likely due to `NODE_AUTH_TOKEN` not in the secrets? But it definitely should cause an error for the headless run

**Comment by runspired** [comment]
@spham92 I don't know if that token was configured for our secrets (I may not have that level of permissions, I'll check) but that it didn't error after ostensibly timing out is problematic. Had it erred we would have gotten a job failed notice to our emails and the bad tag/commit would not have been pushed to master.

**Comment by runspired** [comment]
cc @igorT you will have to configure that token I believe.

**Comment by runspired** [comment]
I believe we may also need to do this

https://github.com/emberjs/ember.js/pull/19445/files

**Comment by spham92** [comment]
@runspired if interested, I have a draft PR for changes to address issues you described. Here's the code to determine next alpha: https://github.com/emberjs/data/pull/7473/files#diff-a47cb342588699a4e59170f23aa9e6262f4168daef2c127485e4fcfa12d8291b and unit test https://github.com/emberjs/data/pull/7473/files#diff-9cf235ccfc0d0e61863933a45416be36059246a4827da1cafb2dc6f3f2ee20a5

**Pull request merged**
