### PR TITLE
[DOC] Fix transform example not using native class syntax

### PR DESCRIPTION
**Pull request by brkn**

### CODE REVIEW

**Review by snewcomer — APPROVED** [review]
Thank you!

**Review by runspired — APPROVED** [review]

**Review by runspired — APPROVED** [review]
We should also document extending EmberObject directly (or using a static create) in a future path. This is also a reminder that we should look into deprecating the Transform base-class as it is essentially a re-export of an extend of EmberObject without any real purpose.

**Comment by jenweber** [comment]
This ticket came up during learning team triage, since it was marked Docs. Can someone with the permissions make the CI re-run? I think the issues with canary that caused failing tests might be resolved now. Thanks!

**Comment by jenweber** [comment]
I asked in dev-ember-data if anyone can re-run these tests.

**Pull request merged**
