### PR TITLE
Failing Test for Accessing Store During Teardown

### PR DESCRIPTION
**Pull request by wagenet**
This is based on a situation in our own app where we were seeing the deprecation warning about accessing a destroyed store. After investigating the stack trace, it became clear that this was not application code accessing the store. Further investigation determined that it was due to interactions between a Proxy (which has observers), view rendering (tracked properties), and the order that records were loaded into the store. This failing test reproduces that scenario.

### CODE REVIEW

**Comment by runspired** [comment]
@wagenet mind rebasing this for me? I suspect we fixed it with array-observer changes but would like to make sure

**Comment by wagenet** [comment]
@runspired done

**Comment by runspired** [comment]
@wagenet thanks! I'm surprised it still fails but I have a suspicion it's because we destroy the store in the test but not the app rendering the records. Is that true to the scenario you hit in your app? Or should we try to update the test to destroy the app rendering the data as well.

**Comment by wagenet** [comment]
@runspired I don't fully remember the context around this, but I did just check and I'm no longer seeing the deprecation warning for this in my app.

**Comment by runspired** [comment]
The test here wasn't destroying the app but only the service while still trying to render objects provided by that service, the failure is expected in that case. Closing since no longer an issue for you, but thanks for the investigative work!

**Pull request closed without merging**
