### PR TITLE
[BUGFIX release] fixes an issue with sync dematerialization followed …

### PR DESCRIPTION
**Pull request by runspired**
…by a findRecord, adds test coverage

### CODE REVIEW

**Comment by stefanpenner** [comment]
restarting CI

**Comment by stefanpenner** [comment]
ah, its possible release/beta branches are in a bad state. This error looks familiar...  @bmac do you remember anything?

**Comment by bmac** [comment]
@stefanpenner I've cherry picked https://github.com/emberjs/data/commit/a36a44ff207a3167b0582ce20c15810126ef3676 into the beta and release branches which I believe fixes the issue.

**Comment by stefanpenner** [comment]
@bmac thought it looked familiar

**Pull request merged**
