### PR TITLE
Bring back ilios partner test

### PR DESCRIPTION
**Pull request by snewcomer**
ref #7744

### CODE REVIEW

**Comment by jrjohnson** [comment]
Ilios Frontend should, once again, be testable here. We're now on 4.1. Turns out there were a few bonus breaking changes we discovered around `hasMany('foo').ids()` which became eventually consistent but no longer consistent on first access. I'm not sure if this was intended or a side effect of that data being tracked (which we love BTW!!). We also ended up pushing a bunch of models into octane style and that sorted out some problems we had with CPs that were returning promises.

**Comment by jrjohnson** [comment]
Well this is fun... ugh. We went to a node 16.x minimum to allow us to do overrides which only seem to work in NPM v8. This is necessary to get around an embroider incompatibility between v0.3somethign and 0.50something. I don't know how to handle that here other than pushing this into it's own job and setting the minimum node version.

**Comment by jrjohnson** [comment]
Ok we were able to resolve our issues with embroiderer and now support node 14.x again. This is probably ready for a re-try.

**Comment by runspired** [comment]
closing in favor of #7529

**Pull request closed without merging**
