### PR TITLE
[CLEANUP beta] Clean up some of the method signatures in RESTAdapter

### PR DESCRIPTION
**Pull request by nlfurniss**
Very small cleanup I noticed could be done after doing my investigation for `ember-fetch`. No fixes or features, so no new tests. Old tests passing locally.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@bmac looks ok to me, do you think this may be an intimate API others are relying on?

**Comment by nlfurniss** [comment]
@hjdivad, @bmac any opinion on this?

**Comment by hjdivad** [comment]
@stefanpenner only `normalizeErrorResponse` is even marked as `@private` in the jsdoc.

`isSuccess` and `isInvalid` seem to be public (whether intentional or not);  I don't think we can really drop the args for these

**Comment by nlfurniss** [comment]
Ahh good point. Doesn't seem worth it in that case

**Pull request closed without merging**
