### PR TITLE
Async filter

### LINKED ISSUE #2181: Store.filter should be made promise aware
Currently there is no way to filter based on relationships. We need to make `store.filter` accept callbacks that return a promise

### PR DESCRIPTION
**Pull request by H1D**
This fixes #2181
Almost done. Need your help.

- [x] implement the stuff
- [x] handle possible race conditions
- [ ] check is it causes performance degradation
- [ ] fix failing tests (looks like it changes records order in array sometimes)

P.S. I won't touch internet till 30 of november. On vacation :tropical_drink:

### CODE REVIEW

**Comment by igorT** [comment]
We  should rebase this against master and fix, @sly7-7 wanna do it?

**Comment by sly7-7** [comment]
@igorT Will try to give it some time this afternoon

**Comment by H1D** [comment]
gonna rebase it to master

**Comment by sly7-7** [comment]
@H1D I have done this this afternoon, unfortunately, did'nt push... here is an almost rebased one though https://github.com/sly7-7/data/tree/async-filter

**Comment by H1D** [comment]
oh! OK

**Pull request closed without merging**
