### PR TITLE
Make _stripIDFromURL() understand URLs like something/:id.format

### LINKED ISSUE #2690: coalesceFindRequests: true got ignored when trying to get a hasMany relationshipts
After upgrading to Ember-data 1.0.0-beta.14, the one request to server from

`parentModel.get(childrenModel)` where just

``` 
parentModel = DS.Model.extend
  childrenModel: DS.hasMany('child', async: true)
```

Ember-data now sends instead of one, n-requests, where n - is a length of childrenModel array of ids. 
I have set `coalesceFindRequests: true` on my adapter.

### PR DESCRIPTION
**Pull request by wecc**
Having URLs like `/posts/1.json` is not an uncommon scenario. This PR makes `_stripIDFromURL()` understand these URLs so coalesced requests can be grouped correctly.

Unsure if RegExp is the right way to go, feedback welcome.

- [ ] Add more asserts to check the actual URLs

Fixes #2690

### CODE REVIEW

**Comment by fivetanley** [comment]
I think it would be great if we could reuse the work in tildeio/route-recognizer.

**Comment by wecc** [comment]
@amiel I know you've been looking at URL related libraries in your work with URL Templates, do you have any suggestions on how to handle this a bit nicer?

Basically we want to check if the URL returned from `buildURL()` ends with `.../{id}`, `.../{id}.format` or `...?id={id}` where `{id}` is the only known part. `...` (and `format`) can be anything.

**Comment by amiel** [comment]
@wecc If we were going to include geriantluff/uri-templates, you could use the ["de-substitution"](https://github.com/geraintluff/uri-templates#guess-variables-from-uri-de-substitution) feature, but I think we're planning to make a uri-template library an optional dependency...

**Comment by wecc** [comment]
Thanks @amiel!

I've looked into [geraintluff/uri-templates](https://github.com/geraintluff/uri-templates) and the de-substitution feature would indeed make this a lot cleaner.

The following patterns match exactly what we're looking for:
- `{/path*,id}`
- `{/path*,id}{.format}`
- `{/path*}{?id}`.

@fivetanley do we want/have the technology to include geraintluff/uri-templates in ED?

**Comment by igorT** [comment]
Closing this for now

**Pull request closed without merging**
