### PR TITLE
raise errors on deprecation

### PR DESCRIPTION
**Pull request by fivetanley**
We shouldn't be committing code that causes deprecation warnings. :(

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1: - But this will likely cause a bunch of issues when testing against canary of Ember during the ramp up to Ember 2.0. :disappointed:

**Comment by pangratz** [comment]
> But this will likely cause a bunch of issues when testing against canary of Ember during the ramp up to Ember 2.0.

One (interim) solution could be to [allow failing builds in `.travis.yml`](http://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-To-Fail) when testing against canary ...

**Comment by bmac** [comment]
@fivetanley do you mind rebasing this pr. I suspect it will pass now.

**Comment by bmac** [comment]
Superseded by https://github.com/emberjs/data/pull/3834

**Pull request closed without merging**
