### PR TITLE
Notify on length when notifying that many-array has changed

### PR DESCRIPTION
**Pull request by grayt0r**
## Description

Port https://github.com/emberjs/data/pull/8413 to 4.6.

### CODE REVIEW

**Comment by grayt0r** [comment]
Hopefully targeting the `release-4-6` branch is the correct approach here, let me know if not.

The original fix didn't come with a test, but I'm more than happy to add one if necessary.

**Comment by grayt0r** [comment]
@runspired would it be possible to get this released? 🙏

**Comment by grayt0r** [comment]
@runspired apologies for chasing, but this is the final blocker before I can get our app onto a more modern version of ember - please could you release `4.6.5`?

**Comment by runspired** [comment]
@grayt0r its hard to release these older versions (a lot of careful manual steps) so sometimes it takes feeling like I've got a free hour or so 🙈

I should be able to get to this later today. In the meantime, `pnpm patch` or yarn patching would let you do your upgrade!

**Comment by grayt0r** [comment]
@runspired thanks for explaining, I didn't mean to assume it was a simple process. I'm currently a bit limited with regards to patching options but realise that's a me problem :)

**Comment by runspired** [comment]
@grayt0r haven't forgotten about you, going to be doing some releases of 4.6 and 4.12 tomorrow

**Comment by grayt0r** [comment]
@runspired awesome, thank you!

**Comment by runspired** [comment]
published!

**Comment by dwickern** [comment]
Model-fragments uses the same code. Do we need to port this fix over there?
https://github.com/adopted-ember-addons/ember-data-model-fragments/blob/316e9be882baf3a9b20b8d6243de3e9fb518beb0/addon/array/stateful.js#L61-L71

**Pull request merged**
