### PR TITLE
Backport empty-object performance improvements from 2.1.0-beta1

### PR DESCRIPTION
**Pull request by jnfisher**
We found these changes substantially improved loading of large datasets in our app.

This PR contains code from the following 2.1.0-beta1 PRs:
#3641 Improve InternalModel (2x - 3x faster)
#3649 Empty object

### CODE REVIEW

**Comment by stefanpenner** [comment]
> We found these changes substantially improved loading of large datasets in our app.

I would be curious to know the #s you have seen in your app with your data.

**Comment by jnfisher** [comment]
In our app we have a large, hierarchical tree of data that is pulled and deserialized when users visit the site.  

To test, we monkey patched these two PRs into the latest 1.13 build of Ember-Data in our app and found loading times improved by 50% (for a dataset containing on the order of hundreds of complex DS.Models with relationships the time to load went from 40s to 20s, roughly).  We still need to make it faster but this was a nice bump for a simple change!

**Comment by stefanpenner** [comment]
@jnfisher good to hear, those numbers still aren't very but our headroom for improvement here is still very high.

It is also worth noting, those two optimizations had a third counter part, one that made OrderSet and Set insertion much faster.
https://github.com/emberjs/ember.js/pull/12061

Which was back-ported to 1.13-stable (but not yet part of a 1.13 release). 

I am curious if you are also utilizing that.

**Comment by stefanpenner** [comment]
@jnfisher when i took a look at this, i also noticed InternalModel tends to allocate many members upfront, event thought not all of them are always needed.

Related issue (I also added some ideas on how to implement) https://github.com/emberjs/data/issues/3644

**Comment by jnfisher** [comment]
I don't recall if we were using stable or release in our testing (we're still on a branch until we clear out some remaining problems with stained-by-children and fragments)-- but we'll keep an eye on it.  

Agree that 10s+ load times are not great.  Fortunately, our users accept waiting for an upfront loading time if the app is fast afterwards.  It's a work in progress.

**Comment by rwjblue** [comment]
> emberjs/ember.js#12061 which was back-ported to 1.13-stable (but not yet part of a 1.13 release)

It was included in 1.13.8.

**Comment by stefanpenner** [comment]
@bmac @igorT @fivetanley @wecc r?

**Comment by igorT** [comment]
I'm a bit concerned we leak NullObjects to user space. People might be surprised by that? @stefanpenner any thoughts? Should be simple to wrap `changedAttributes` to avoid that, and the perf impact would be minimal

**Pull request merged**
