### PR TITLE
Do not re-add deleted records to a hasMany relationship

### LINKED ISSUE #2666: adding and removing records from hasMany relationship broken.
I am experiencing strange behavior in the latest version (1.0.0-beta.14.1) of ember data. 

It appears that items removed from a hasMany collection reappear when adding new items.

Checkout the following jsbin http://jsbin.com/boluba/13

Remove an Item then add an item, the removed item will reappear.  The strange thing is the item is not in the store when using the ember inspector.

### PR DESCRIPTION
**Pull request by bmac**
Closes #2666

Thanks to @dwickern for the excellent test case. 

@igorT if you have time I'd love to get your eyes on this

### CODE REVIEW

**Comment by fivetanley** [comment]
LGTM, I'm a little concerned at using slice here though instead of just filter (filter returns a new array). Is this a JS array or one of ember's array-likes?

**Comment by bmac** [comment]
Good call @fivetanley. It was a JS array so I have updated the pr to use the filter function form `Ember.ArrayPolyfills`.

**Comment by arenoir** [comment]
@bmac yep that works.  :+1:

**Comment by tonywok** [comment]
Ah, nice, our team was investigating this as well. :+1:

**Comment by tomdale** [comment]
@igorT is working on a more comprehensive solution, and will make sure to include this test case in his in-progress work.

**Comment by tonywok** [comment]
@tomdale Is the fix @igorT is working on scoped to just this issue? Or something larger? If larger, is there a branch I can follow along with? Thanks :)

**Comment by bmac** [comment]
@igorT anything I can do to help with move your work on this along?

**Comment by bmac** [comment]
I recognize that this is a bandaid fix however I'm going to merge it as its holding people back from upgrading past Ember Data beta.12 which will soon be broken with the release version of ember (1.11) due to some changes in Ember.Map.

**Comment by davidlormor** [comment]
Just want to confirm that this patch got rid of my bug, and allowed me to get rid of a poorly implemented workaround. Thanks! :+1:

**Comment by drewcovi** [comment]
@bmac does this fix also account for simply removing a record from a relationship and then saving that record? I'm seeing records re-appear and checking record.get('isDeleted') will not register in that case (since we're not destroying a record)

**Comment by codylettau** [comment]
@drewcovi has there been any update with the issue you are seeing in regards to only removing (not deleting) object in many-to-one relationships? We are encountering this same exact issue as well.

**Comment by drewcovi** [comment]
@codylettau I've logged a new bug here: https://github.com/emberjs/data/issues/3027

From what i can tell this is definitely a bug.

**Comment by denisbetsi** [comment]
This is a major bug, making a part of the project totally unusable. There's no work arounds that are clean. If using any sort of a front end tool like strongloop which depends on creating relationships between records, this creates a havoc.

**Comment by denisbetsi** [comment]
Found a temporary work around, 

Prior to deleting items from hasMany I create a new field called deleted and set it to 1

```
     that.get("productBundles").forEach(function(olditem){
              olditem.set("deleted",1);
              olditem.destroyRecord();
     });
```

Then I extend DS.RESTSerializer, I also have to change the relationship key in my case to end with Id vs standard ember handling so it's not related to this hack

```
App.ApplicationSerializer = DS.RESTSerializer.extend({
	serialize: function(record, options) {
	    record.eachRelationship(function(name, relationship) {
	      if (relationship.kind === 'hasMany'||relationship.kind === 'belongsTo') {
	      	var singular = name.singularize() + 'Id';
	      	if(name.endsWith("s")&&typeof record.get(name) != 'string' &&relationship.kind === 'hasMany'){
	        	json[singular] = (record.get(name)?record.get(name).filter(function(item){return !item.record.deleted}).mapBy('id'):[]);
	      	}else{
	      		if(record.get(name)&&record.get(name).get("id"))
		      		json[singular] = (record.get(name)?record.get(name).get('id'):'');
	      	}
	      }
	    });
	    return json;
	}
});
```

So prior to saving the record, I look for deleted and filter them out and overwrite the request

```
record.get(name).filter(function(item){return !item.record.deleted})
```

Now I am battling another yet unexplained  that.get("productBundles").invoke('destroyRecord') leaves 1 record in the array and just doesn't issue delete command on it. 

Some days I absolutely love Ember and this isn't one of those days. The simplest thing becomes a 2 day hackathon in finding a workaround to what should be a solid feature after years of development. ARGGH!!

**Comment by dwickern** [comment]
@denisbetsi Are you on the latest version of ember-data? This should be fixed now.

**Comment by denisbetsi** [comment]
I tried using this version //builds.emberjs.com/beta/ember-data.js

**Pull request merged**
