### PR TITLE
Adding test unregister model

### PR DESCRIPTION
**Pull request by Leooo**
- [x] adding failing test for https://github.com/emberjs/ember.js/issues/15268

(uncomment `//delete owner.__container__.factoryCache['model:baz'];` and the test passes)

### CODE REVIEW

**Comment by stefanpenner** [comment]
awesome. Mind squashing though, lots of random commits in this one.

**Comment by Leooo** [comment]
Thats because I was working on the 2.10 tag when I added my test, then had to merge upstream to do a cleaner PR to master. PR wont be merged anyway as test is failing for now, thats just to show the test. I can start a new branch if you want, with one commit, but at least thats enough to see the failing test for now. Let me know.

**Comment by runspired** [comment]
@Leooo could you rebase this against master with only the necessary test submission commit?

**Comment by Leooo** [comment]
@runspired done in https://github.com/emberjs/data/pull/5443, closing this one thanks

**Pull request closed without merging**
