### PR TITLE
Use object literal methods

### PR DESCRIPTION
**Pull request by Turbo87**
Babel will transpile them into the previous syntax
(see https://babeljs.io/docs/learn-es2015/#enhanced-object-literals)

### CODE REVIEW

**Comment by igorT** [comment]
Thanks for the PR. I feel that object literal methods make searching through the code base significantly harder, so would not want to switch to them for a while, until our tooling becomes better. Thanks!

**Comment by Turbo87** [comment]
could you elaborate on why you find it harder with object literal methods?

**Comment by igorT** [comment]
If you want to search for where serialize is defined normally you can just search for 'serailize:`, with object literal methods you need to use a javascript parser in command line/editor, and good luck in chrome scripts if you use source maps

**Comment by Turbo87** [comment]
ah, I see... so the reason is that method definition and method calls would then look similar to a plain text search.

I guess one could take advantage of the fact that methods are usually indented and method calls are prefixed with something like `this.someMethod()`. In theory that would allow searching for <code>&nbsp;&nbsp;serialize(</code> to find the method definition, right?

Please don't take my questions the wrong way. I'm not trying to convince you of anything, I'm just trying to understand why you don't want to use that feature.

**Comment by rwjblue** [comment]
yes, you could search for `/\s+serialize[(:]/g` to find either instances, but that is a ton more work than just searching for `serialize:` :smile: 

Demo: http://regexr.com/3b4ph

**Comment by Turbo87** [comment]
lol, it's obviously more complicated if you want to search for **both** styles ;)

**Pull request closed without merging**
