### PR TITLE
Rename and deprecate finders (store.all -> store.peekAll and store.getById -> store.peekRecord)

### LINKED ISSUE #3205: Rename and deprecate store.all/store.getById
`store.getById` should be renamed to `peekById`.

`store.all` should be renamed to `store.peekAll`.

For both of these methods we still need to support the old api with a deprecation warning recommending the use of the new name.

Docs and guides will also need to be updated.

### PR DESCRIPTION
**Pull request by HeroicEric**
closes #3205

### CODE REVIEW

**Comment by bmac** [comment]
Hi @HeroicEric. Now the consensus is `peekById` should be renamed to `peekRecord`. Do you mind updating this pr to reflect that change?

Thanks and sorry about making you redo some of this work.

**Comment by HeroicEric** [comment]
@bmac sure

**Comment by HeroicEric** [comment]
@bmac do you have a link to that discussion?

**Comment by bmac** [comment]
@HeroicEric https://github.com/emberjs/rfcs/pull/27#issuecomment-109629672

**Comment by HeroicEric** [comment]
@bmac this should be good to go now. Docs are waiting at https://github.com/emberjs/guides/pull/346

**Comment by bmac** [comment]
:tada:

**Comment by sandstrom** [comment]
Nice! :boat:

**Pull request merged**
