### PR TITLE
add test coverage for more node versions (node 4)

### LINKED ISSUE #5198: Enable Node 4 in travis
# Motivation

FastBoot and other fastboot compatible addons run their tests against a canary version of Ember data with Node 4 support. Current Ember Data isn't being tested in Node 4 in CI. This is causing things to be not caught early. We should have Node 4, Node 6 enabled in travis.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #5198

### CODE REVIEW

**Comment by kellyselden** [comment]
Blocked on https://github.com/heimdalljs/heimdall-query/pull/1

**Comment by kellyselden** [comment]
This is ready to merge, or we can wait for @runspired or @hjdivad to release https://github.com/heimdalljs/heimdall-query.

**Comment by bmac** [comment]
I'd prefer to wait for a release of https://github.com/heimdalljs/heimdall-query. @hjdivad / @runspired is there a preferred time to ping you to nudge for a release?

**Comment by kellyselden** [comment]
@bmac unforked and rebased. Ready for review.

**Comment by bmac** [comment]
Thanks @kellyselden.

**Pull request merged**
