### PR TITLE
[BUGFIX release] Remove deprecation warning for dev, keep IE 8 compat

### LINKED ISSUE #3465: Ember.keys and Ember.create deprecated in 1.13
Using release Ember Data with release Ember currently causes a bunch of deprecation warnings in the console.

http://output.jsbin.com/losona

### PR DESCRIPTION
**Pull request by sly7-7**
Closes #3465

cc/ @bmac @stefanpenner

### CODE REVIEW

**Comment by wecc** [comment]
Would it make sense to export `create` and `keysFunc` from a separate module and import instead of having `Object.create || Ember.create` / `Object.keys || Ember.keys` everywhere?

**Comment by sly7-7** [comment]
@wecc Not sure if it's worth it, but it maybe be good for further refactorings.

**Comment by bmac** [comment]
Looks good to me. I think the build failure might be fixed by https://github.com/emberjs/data/commit/6f1a6f8f0957dd639e5d00e4d2ee87446152e80d. I can cherry pick that over to the release branch in the morning when I'm on my laptop.

**Comment by sly7-7** [comment]
@bmac I cherry picked your commit in that branch and force pushed. Now failing for a good reason.

**Comment by sly7-7** [comment]
@bmac, instead I've created https://github.com/emberjs/data/pull/3478 with your fix, and also update tests here (we can't import modules in tests)

**Pull request merged**
