### PR TITLE
[fix] Add json:api header on every requests

### PR DESCRIPTION
**Pull request by dcyriller**
This is a port of https://github.com/emberjs/data/pull/5999 to 3.9

### CODE REVIEW

**Comment by runspired** [comment]
hrm, unsure why appveyor and travis are being bad here. I will have to dig in.

**Comment by dcyriller** [comment]
I've added a commit which is a port of https://github.com/emberjs/data/pull/6006 to release branch. It activates CI's `test` and `additional tests` for release and lts branches.

**Comment by dcyriller** [comment]
I've revert the last commit as it would put too much pressure on the CI 🙂

**Comment by bryanhickerson** [comment]
@dcyriller what release of ember 3.9 is this in? I can't tell from the CHANGELOG/commit history, so forgive me if it's obvious.

**Comment by runspired** [comment]
@bryanhickerson probably 3.9.1 but definitely 3.9.2. The PR wasn't labelled correctly to be picked up by the changelog generation unfortunately.

**Comment by runspired** [comment]
Confirmed it is in 3.9.1

**Pull request merged**
