### PR TITLE
[PERF] Guard against poorly optimized babel output

### PR DESCRIPTION
**Pull request by runspired**
This PR will fail to build until we have fixed all the locations in which our babel compilation step is producing sub-optimal output to handle `let` and `const` closures.

When this PR is green, we can merge it and gain perfs.

cc @stefanpenner

### CODE REVIEW

**Comment by stefanpenner** [comment]
the thrown error is good (from ci):

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
SyntaxError: ember-data/serializers/rest.js: Compiling let/const in this block would add a closure (throwIfClosureRequired).
  254 |     let keys = Object.keys(payload);
  255 | 
> 256 |     for (let i = 0, length = keys.length; i < length; i++) {
      |                                                            ^
  257 |       let prop = keys[i];
  258 |       let modelName = prop;
  259 |       let forcedSecondary = false;
```

**Comment by stefanpenner** [comment]
@runspired should i fix?

**Comment by runspired** [comment]
@stefanpenner yes. However, it stops the build on the first error encountered, you may just encounter the next one :)

**Comment by stefanpenner** [comment]
looking now

**Comment by stefanpenner** [comment]
this made me finally fix: https://github.com/stefanpenner/broccoli-persistent-filter/pull/106/commits/d7ab2d1708c16b4f851c32e4f6611e0412bfb702 :trollface:

**Comment by stefanpenner** [comment]
oops broke something...

**Comment by stefanpenner** [comment]
> oops broke something...

fixed locally, lets see what `try` says.

**Comment by runspired** [comment]
Thanks @stefanpenner :)

**Pull request merged**
