### PR TITLE
Functional update for adapter populated record arrays

### PR DESCRIPTION
**Pull request by vinilios**
permit for adapter populated record array contents to be updated by
calling `update` method.

Refs emberjs/data#3082

### CODE REVIEW

**Comment by bmac** [comment]
Ping @igorT. Do you mind reviewing this pr?

**Comment by tchak** [comment]
LGTM. I think we could also at some point deprecate `update` in favor of `reload`. If doing so, we should also deprecate / remove `isUpdating`.

**Comment by wecc** [comment]
LGTM too :+1: 

Would you be able to have a look at resolving the merge conflicts and aldo prefix the commit with `[BUGFIX beta]`?

**Comment by fivetanley** [comment]
I updated this as #4050. Thanks for the contribution!

**Pull request closed without merging**
