### PR TITLE
Remove feature flagging for ds-extended-errors.

### PR DESCRIPTION
**Pull request by rwjblue**
The feature was enabled in ember-data@2.13, the feature flagging can now be removed.

This is a work around to a bug in the feature flagging system used by ember-data, that will need to be fixed on master branch.

Fixes https://github.com/emberjs/data/issues/5020.

Note: this targets `release` branch.  I'll submit a forward port for `beta`/`master`.

### CODE REVIEW

**Comment by urbany** [comment]
Hi @rwjblue will this make it to the 2.15 release?
Thank you so much in advance!

**Comment by bmac** [comment]
rebased as https://github.com/emberjs/data/pull/5191. Sorry for the delay @rwjblue.

**Comment by ashrafhasson** [comment]
I'm encountering this with ember-data 2.15 :(

**Comment by bmac** [comment]
I'll try to cut a 2.15.2 release later today. This pr didn't make it into  2.15.1.

**Comment by sihuang** [comment]
@bmac did it make 2.15.2 or any later build?

**Comment by bmac** [comment]
Yes. Its in [2.15.2](https://github.com/emberjs/data/commits/v2.15.2) and [2.16.0](https://github.com/emberjs/data/commits/v2.16.0).

**Comment by sihuang** [comment]
@bmac thanks for updating.

**Pull request closed without merging**
