### PR TITLE
[DOC] improve urlForFindAll example

### PR DESCRIPTION
**Pull request by mcfiredrill**
While the example provided is valid, I think a slightly more fleshed out
example of usage might be more helpful for newcomers.

### CODE REVIEW

**Comment by efx** [comment]
@mcfiredrill thanks for contributing! 
longer-term we are trying to clean up all of these embedded examples to make ember-data's API documentation coherent and polished.  (tl;dr here: https://www.notion.so/QUEST-issue-documentation-draft-94444df09d804ae7bce9665401f462be). We'll be putting together the actual QUEST issue soon.

**Comment by mcfiredrill** [comment]
@efx Thanks for the link! I'd love to help out with that effort if I can.

**Comment by efx** [comment]
@mcfiredrill awesome, that would be greatly appreciated. I will cc you once I create the QUEST 😄

**Comment by Gaurav0** [comment]
LGTM

**Pull request merged**
