### PR TITLE
Fixed Windows CI

### PR DESCRIPTION
**Pull request by johanneswuerbach**

### CODE REVIEW

**Comment by stefanpenner** [comment]
woohoo, im excited for this to land

**Comment by johanneswuerbach** [comment]
Looks like it is working now. There are a bunch of style errors now :cry:, but they seem unrelated.

**Comment by johanneswuerbach** [comment]
//cc @seanpdoyle I saw that you implemented style checking, could you give me a hint?

**Comment by rwjblue** [comment]
@johanneswuerbach - See https://github.com/emberjs/ember.js/pull/10380 for a bit of background on new JSCS failures.  There was a JSCS update that fixed a number of parse errors (that caused whole swaths to be ignored).

**Comment by bmac** [comment]
You rock @johanneswuerbach! \o/

**Comment by bmac** [comment]
@johanneswuerbach jscs issues are now corrected on master and the canary tests are fixed. Could you rebase this pr and remove the disable canary code?

**Comment by johanneswuerbach** [comment]
Thanks @bmac. Now we are green :green_heart:

**Comment by stefanpenner** [comment]
woohoo thanks a bunch!

**Pull request merged**
