### PR TITLE
Move the date import to where it is used intead of the root module

### PR DESCRIPTION
**Pull request by bmac**

### CODE REVIEW

**Comment by pangratz** [comment]
I wonder if `Ember.Date` should be removed as a whole an only the `parse` part should be imported? `Ember.Date` shows up in the API doc, but it only has the `parse` function, and doesn't extend JS `Date`. 

I am not sure what the correct way would be though, semver-wise. Maybe deprecate it for `3.0`?

**Comment by rwjblue** [comment]
We can provide a public module for date parsing, I know some users rely on `Ember.Date.parse` existing...

**Comment by bmac** [comment]
I opened an issue to track the Date.parse comments outside of this pr.

**Comment by pangratz** [comment]
> I opened an issue to track the Date.parse comments outside of this pr.

:+1:

**Pull request merged**
