### PR TITLE
Allow the store to lookup the applicationAdapter using adapterFor

### LINKED ISSUE #2925: 1.0.0-beta.16 is looking for an application model
```
Error: No model was found for 'application'
    at new Error (native)
    at Error.EmberError (http://localhost:7357/assets/vendor.js:21836:23)
    at ember$data$lib$system$store$$Service.extend.modelFor (http://localhost:7357/assets/vendor.js:78603:19)
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:7357/assets/vendor.js:78974:21)
    at DS.Store.reopen.usingFixtureAdapter (http://localhost:7357/assets/test-support.js:5973:26)
    at DS.Store.reopen.pushPayload (http://localhost:7357/assets/test-support.js:6204:16)
    at superWrapper [as pushPayload] (http://localhost:7357/assets/vendor.js:27582:22)
    at http://localhost:7357/assets/garaje.js:5901:22
    at tryCatch (http://localhost:7357/assets/vendor.js:59834:16)
    at invokeCallback (http://localhost:7357/assets/vendor.js:59846:17)
```

The usage that caused this was an innocent `this.store.pushPayload('subscription', data)`.

### PR DESCRIPTION
**Pull request by bmac**
Closes #2925

cc @igorT @jmurphyau

### CODE REVIEW

**Comment by stefanpenner** [comment]
is this a regression in beta 16? Basically, im wondering if i need to wait for this to land before releasing the new ember-cli that bundles beta 16

**Comment by bmac** [comment]
Yes this is a regression in beta 16. `adapterFor` is marked as private in the api docs but this seems like a common enough pattern that I might release a beta 16.1 with this fix.

**Comment by stefanpenner** [comment]
@bmac do you have a planned eta? Should I hold-off ember-cli release today?

**Comment by bmac** [comment]
I was going to wait a day to see what other issues get reported. If you'd like to release ember-cli today feel free to revert my pr adding beta 16 we can always update it for the next release.

**Comment by stefanpenner** [comment]
does beta 16 fix that deprecation ? or is that 15

**Comment by kamal** [comment]
@stefanpenner that's gone in 16

**Comment by jmurphyau** [comment]
Should the same be done for serializerFor - it would throw the same error if 'application' were to be passed in

**Comment by bmac** [comment]
Good call @jmurphyau

**Pull request merged**
