### PR TITLE
[WIP] Convert unload test to json api format for `store.push`

### PR DESCRIPTION
**Pull request by stevenwu**
I want to make sure I'm on the right track. #3223

### CODE REVIEW

**Comment by wecc** [comment]
@stevenwu Almost. You seem to be passing JSON-API Resouce Objects but new `store.push()` expects a full JSON-API Document.

Example for a single record:

```js
store.push({
  "data": {
    "id": "1",
    "type": "record",
    "attributes": {
      "title": "Toto"
    }
  }
});
```

Example for a multiple records:

```js
store.push({
  "data": [{
    "id": "1",
    "type": "record",
    "attributes": {
      "title": "Toto"
    }
  }, {
    "id": "2",
    "type": "record",
    "attributes": {
      "title": "Dorothy"
    }
  }]
});
```

**Comment by igorT** [comment]
@wecc I feel like we should support passing a single resource object to push. What do you think?

**Comment by igorT** [comment]
This was merged right?

**Comment by stevenwu** [comment]
No, I closed it when I saw the PR from @wecc.

**Pull request closed without merging**
