### PR TITLE
unload should invalidate async hasMany: failing test

### PR DESCRIPTION
**Pull request by jlami**
This simulates the problems I'm having when trying to debug #5343 

As far as I could tell the new behaviour for async relationships is not to mark unloaded items as deleted, but to use `invalidate+refetch` as mentioned here: https://github.com/emberjs/data/commit/6e8a23656cb073596cd951bdab9ca0541d1bcbe3
But I'm having trouble understanding whether the invalidate should be done by the ember-data user, or by ember-data.
I feel this should be ember-data's job, but this test has one line in comment where the user could `hasMany(....).reload()` to refetch the data to fix the problem. But that feels like a bad solution.

### CODE REVIEW

**Comment by jlami** [comment]
Might be related to #5328

**Comment by jlami** [comment]
@sly7-7 I think the problem here is partly due to me not understanding the new async handling. The first assert of the count not being correct after the unload could probably be ignored. But the final exception might be the real problem.

Where ember-data now correctly is able to reload an dematerialized record that is still in the ManyArray, it fails to handle the case when a record is deleted on the server side. The rejected fetch will result in a complete failure now, while this could actually be a valid response. So maybe this test should be renamed into 'async relationship can handle server side deletion' or something like that?

**Comment by jlami** [comment]
Does anybody have any idea on how a rejection in a loading ManyArray should be handled in async relationships? The async part makes it valid to have changes on the server side once the data is asked for. So I think ember-data should play well with any record that is rejected.

The findMany part only gives warnings if you don't include deleted items as far as I can tell: https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L892
But this path is only used if coalesceRecords is true I believe.

We don't coalesce records in our plugin and this path seems to throw exceptions that are not caught and I'm not really sure if this will actually update the ManyArray if it would be used with a `model.get('manyArray').catch(...)`. And even if this would work, computed properties don't work this way. So I really think the ManyArray should handle this when reloading. Maybe here: https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/has-many.js#L290

**Comment by runspired** [comment]
@bmac we can close this as fixed by #5377

**Pull request closed without merging**
