### PR TITLE
Remove todo in API doc

### PR DESCRIPTION
**Pull request by bmac**

### CODE REVIEW

**Comment by wecc** [comment]
:+1:  `[DOC release]`?

**Comment by bmac** [comment]
@wecc I left the DOC release out because this is going directly into the release branch. Let me know if I should add it.

**Comment by wecc** [comment]
I don't feel strongly about it. Will it make releasing confusing since it's not supposed to go in beta?

**Comment by bmac** [comment]
No. I don't have to cherry pick it anywhere so release is easy.

**Pull request merged**
