### PR TITLE
[BUGFIX 3.12] Backport Symbol fix

### PR DESCRIPTION
**Pull request by dcyriller**
Port https://github.com/emberjs/data/pull/6389 to 3.12

This solves will close https://github.com/emberjs/data/pull/6389

~~🚧 We have to re-target this PR against a `release-3.12` branch, that need to be created. ⚠️~~ EDIT: done

### CODE REVIEW

**Comment by rwjblue** [comment]
@dcyriller `release` _is_ 3.12 (we only make the `release-x-y` branches when the specific release **is not** the current release).

**Comment by rwjblue** [comment]
Changed target, and kicked off CI again.

**Comment by dcyriller** [comment]
Okay! Thanks

**Comment by runspired** [comment]
I opened #6425 yesterday because I noticed the same failure @dcyriller, it is unrelated to this.

**Comment by runspired** [comment]
We should also backport this to beta

**Pull request merged**
