### PR TITLE
Lock ember-cli-htmlbars to 1.3.0 to get the build passing again

### PR DESCRIPTION
**Pull request by bmac**

### CODE REVIEW

**Comment by stefanpenner** [comment]
thanks. I should have done this sooner myself, but this is the right interim step. I'll still get to the bottom of the root cause, but lets land this when green.

**Comment by stefanpenner** [comment]
appveyor looks to have run, but then hung at the end. Although everything appears to have passed?

**Comment by rwjblue** [comment]
@stefanpenner - Let me know if you think we need to do something on the ember-cli-version-checker or ember-cli-htmlbars sides...

**Comment by stefanpenner** [comment]
@bmac / @Igort can either of you guys restart the appveyor job, it appears I don't have permissions for this appveyor account for some reason.

**Comment by bmac** [comment]
@igorT is the only one who can restart appveyor jobs. I usually ignore the appvayor failings when it looks like a result of appveyor hijinks.

**Pull request merged**
