### PR TITLE
Rename Snapshot to AdapterSnapshot

### PR DESCRIPTION
**Pull request by HeroicEric**
fixes https://github.com/emberjs/data/issues/3285

- [x] Rename `Snapshot` to `AdapterSnapshot`

### CODE REVIEW

**Comment by igorT** [comment]
record._createSnapshot is private no need to deprecate

**Comment by HeroicEric** [comment]
@igorT I was just thinking it might be nice since there are some popular addons that are using it.

- https://github.com/lytics/ember-data.model-fragments
- https://github.com/kurko/ember-json-api
- https://github.com/clintjhill/ember-parse-adapter

to name a few

**Comment by igorT** [comment]
well end up with a public hook later, so would rather not rename fo rnow

**Comment by HeroicEric** [comment]
You'd rather not rename `Snapshot` or `Model#_createSnapshot`?

**Comment by igorT** [comment]
_createsnapshot

**Comment by bmac** [comment]
Thanks for the pr @HeroicEric. Unfortunately, the Ember Data team has decided to stick with the name `Snapshot`.

**Pull request closed without merging**
