### PR TITLE
Release 4.0

### PR DESCRIPTION
**Pull request by igorT**

### CODE REVIEW

**Comment by ef4** [comment]
Please see #7785 which targets this branch. I'm hoping we can get that change in.

**Comment by snewcomer** [comment]
@ef4 Can we cherry pick to this branch?

**Comment by ef4** [comment]
I'll update my PR now that you fixed the test failures here, just to make sure there's no need failures I introduced. Then once it's ready, we can just merge it (it targets this PR).

**Comment by ef4** [comment]
@snewcomer we can just hit merge on that PR whenever and it will end up on this branch. I would do it, but I wanted to get an OK from somebody else first and not just ram it through with no review.

**Comment by snewcomer** [comment]
Will merge and release today

**Pull request merged**
