### PR TITLE
Remove module-unification blueprints

### PR DESCRIPTION
**Pull request by dcyriller**
This experiement has been disabled in Ember, meaning it can't be used anymore (starting from `ember-source@v3.12.0-beta.1`).

### CODE REVIEW

**Comment by rwjblue** [comment]
FYI - ember-cli is working towards removal as well (see https://github.com/ember-cli/ember-cli/pull/8820)

**Comment by rwjblue** [comment]
Looks like the CI failures are legit (probably blueprint tests?), you should be able to repro by running `lerna run test:node`.

**Comment by dcyriller** [comment]
Thank you for the tip. I missed a few tests that need to be updated.

**Comment by dcyriller** [comment]
It should be good now! Sorry for the run aounrd @rwjblue

**Pull request merged**
