### PR TITLE
Addonize

### PR DESCRIPTION
**Pull request by fivetanley**
todo:

- [x] get booting as an addon
- [x] fix tests and their import paths
- [ ] rewrite the build for the globals file to use Babel and the defeautureify replacement by @mmun
- ???
- profit

### CODE REVIEW

**Comment by fsmanuel** [comment]
@fivetanley do you need any help or feedback on that? :+1:

**Comment by fivetanley** [comment]
@fsmanuel yeah that's what peerDependency does

**Comment by stefanpenner** [comment]
@fivetanley it doesn't in v3

**Comment by fivetanley** [comment]
as they should...?

**Comment by stefanpenner** [comment]
v2 auto-installed, v3 does not.  Just making sure this was known

**Pull request merged**
