### PR TITLE
fix initial polymorphic attribute

### PR DESCRIPTION
**Pull request by sly7-7**
Maybe I'm missing something, but it seems weird for a relationship to be polymorphic by default, right ?

### CODE REVIEW

**Comment by bmac** [comment]
@hjdivad would you have time to review this pr?

**Comment by rwjblue** [comment]
Would you mind adding a regression test, to help ensure we don't make this mistake again...

**Comment by sly7-7** [comment]
The thing is I don't even know if this property is used at all. I think (maybe wrongly) if it was used, some existing tests would already be failing. I will investigate more asap.

**Comment by sly7-7** [comment]
@runspired Ok, I also removed the initialization of the `isPolymorphic` attribute from the HasManyRelationship class. In that case, without the right initialization to 'false' in the parent class, some tests are failling.

**Comment by runspired** [comment]
Thanks! so the TLDR for anyone following along was that our tests passed bc the extended class (has-many) also initialized `isPolymorphic` clobbering our mistake. By fixing the mistake we removed the dual initialization.

**Pull request merged**
