### PR TITLE
address the syntax error with decorators in tests

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Addresses: https://github.com/emberjs/data/issues/6002
- Fixes decorator syntax error

### CODE REVIEW

**Comment by igorT** [comment]
@NullVoxPopuli thanks for this! It fails with ember 3.4 though.

**Comment by runspired** [comment]
@pzuraq does the polyfill support 3.4?

**Comment by NullVoxPopuli** [comment]
looks like it's an issue with some classic syntax. 

in the failing test if I convert the classic model from

```ts
Model.extend({ 
  name: attr() 
});
```
to
```ts
class extends Model {
  @attr() name;
}
```
it passes

**Comment by runspired** [comment]
@NullVoxPopuli weird that only one test fails for that reason, there's likely an extenuating circumstance. We should investigate so that if there is an issue with the polyfill it can be improved.

**Comment by NullVoxPopuli** [comment]
Just starting with some tests here: https://github.com/pzuraq/ember-decorators-polyfill/pull/12

**Comment by NullVoxPopuli** [comment]
Now that the C.I. has finished, and it's a new day, I can confirm that the issue is _likely_ with the polyfill. So, excellent. I don't have time today to keep investigating this, but I can keep poking here and there as I have little time pockets.

**Comment by runspired** [comment]
Looks like the PR to ember-decorators-polyfill was merged so bumping the version should unblock this :) 

Sidenote there seems to be an issue with CI right now, someone will need to investigate.

**Comment by NullVoxPopuli** [comment]
re: failing C.I.:
ember-m3 has a linting error
factory-guy broke entirely

**Pull request merged**
