### PR TITLE
[TEST] - Unload record clears the current state of a has many relationship

### PR DESCRIPTION
**Pull request by lsg-braymon**
This is a test case for issue: https://github.com/emberjs/data/issues/6146

### CODE REVIEW

**Comment by runspired** [comment]
Roughly speaking this is an interesting artifact of a very long standing issue that I have a (reasonable) amount of hope that I'll be able to fix in the next few months combined with an expected behavior.

I'll start with a short explanation of the long-standing issue: there's some additional info about that in this long twitter thread: https://twitter.com/Runspired/status/1058536977597775872

Roughly the issue is that how we currently cache and operate on the state of the graph is too lossy, and leads to situations where we are both unable to apply patches correctly and unable to preserve local state when updating information from a remote source is required. This is something we can *largely* fix with a good bit of refactoring, and for the cases we can't eventually we will expose capabilities to users that allow them to signal to use enough information to get it right 100% of the time.

Now, for the expected behavior:

`unloadRecord` moves a record into a "never-loaded" state. It does not purge references to that record from the cache unless there are no retainers (relationships, especially async relationships, are retainers).

When a record is unloaded, for async relationships this causes us to trigger a re-fetch to re-load if the record is still needed and the relationships is accessed.

For sync relationships we do a (bit of an odd) thing by treating it as a signal that we can fully purge the record. We do this not because of correctness (it's not a correct thing to do) but because for a long time buggy behavior in unload effectively allowed users to treat it as such and it became widely depended upon.  When we apply this "canonical delete", we end up doing a re-sync of our remaining "known good remote state" to our current state. This is where the buggy behavior mentioned above causes this issue for sync relationships. For async relationships the buggy behavior would manifest only once the re-fetch completes.

If you convert this test to a `TODO` (there are other examples in the code-base to pull from) I'll merge it as the test looks solid. I don't think we'll be able to address this for a matter of months however.

**Comment by lsg-braymon** [comment]
@runspired The test has been converted to a `TODO`. Thanks!

**Comment by runspired** [comment]
I suspect all the refactoring I did in the relationship layer may have resolved this, I'll make sure to get this test merged next week to check.

**Comment by runspired** [comment]
I didn't have permissions to rebase the original so I've reopened this in a new PR #8160

**Pull request closed without merging**
