### PR TITLE
[BUGFIX beta] Upgrading ember-inflector to v3.0.0

### PR DESCRIPTION
**Pull request by sumeetattree**
Fixes: #5529 

No changes required to `import` statements

### CODE REVIEW

**Comment by bmac** [comment]
The test failures seem unrelated to this change. I just kicked travis to retry the failing builds again.

**Comment by sumeetattree** [comment]
@bmac Thanks! I noticed 4 failures in master branch. I should have mentioned that. Doh!

Updated the title because bumping it to `3.0.0` and not `3.3.0`

**Comment by rwjblue** [comment]
Thank you!

**Comment by runspired** [comment]
Thanks @sumeetattree !

**Pull request merged**
