### PR TITLE
Implement dirty tracking and rollback of belongsTo relationships.

### PR DESCRIPTION
**Pull request by arenoir**
Issues #3696, #3045

### CODE REVIEW

**Comment by fivetanley** [comment]
This looks good to me. Would prefer for @wecc or @igorT to review though. Great work!

**Comment by svox1** [comment]
Any news on this? Would be great if releationships can rollback again.

**Comment by ptgamr** [comment]
+1

**Comment by fivetanley** [comment]
@arenoir sorry for the delay, I'll make sure it gets discussed at this week's meeting.

**Comment by fivetanley** [comment]
@igorT has agreed to write an RFC for relationship tracking.

**Comment by lkhaas** [comment]
+1 on this issue

**Comment by arenoir** [comment]
@fivetanley any word on this? fyi I rebased with master.

**Comment by nicksteffens** [comment]
:+1:

**Comment by Keeo** [comment]
Please :+1:

**Comment by thedrew12** [comment]
+1

**Comment by fivetanley** [comment]
@arenoir I pinged @igorT about this yesterday. He said he should be able to write an RFC for an alternative approach. Hopefully he can fill in here more when he has a chance...

**Comment by fivetanley** [comment]
I apologize for the long delays

**Comment by arenoir** [comment]
No worries @fivetanly, I look forward to the RFC.  Perhaps I am beating a dead horse but @igorT would you take a look at the [conversation](https://github.com/emberjs/data/issues/3696) I started regarding the difference between hasOne and belongsTo.  I think it relates to the RFC you may be putting together.

**Comment by aaronbhansen** [comment]
:+1: this would be useful

**Comment by fivetanley** [comment]
We all agree it would be useful. ;)

**Comment by nanuxbe** [comment]
:+1: I've been implementing an re-implementing this for ages every time ember-data changes. It would definitely be useful.

**Comment by bmac** [comment]
I'm going to close this pr. @igorT is working on an RFC to describe what needs to happen to for Ember Data to support relationship rollback for both `hasMany` and `belongsTo`.

**Comment by epyx25** [comment]
> I've been implementing an re-implementing this for ages every time ember-data changes.

@nanuxbe could you share to us in a gist?

**Comment by nanuxbe** [comment]
@epyx25 this is one of the implementations: https://gist.github.com/nanuxbe/f6426390f19abdf6f909118067380a7e

It is for an EmberData 1.x application. This technique doesn't currently work with EmberData 2.x but it might be a good lead to start with and replicate using InternalModel in Ember 2.x. I've looked a bit into it and as far as I recall, belong_to's initial state aren't store when model is initialized in EmberData 2.x So you'd also have to update that part. You can probably also look at the application serializer and try to store initial relationships at that point.

If you look around, there are many other people who have done somewhat the same thing.

**Comment by epyx25** [comment]
@nanuxbe thanks!

**Comment by arenoir** [comment]
@epyx25 you can directly install this branch or fork it branch it and include it in your package.json

```
//package.json

"devDependencies": {
  "ember-data": "git://github.com/arenoir/data#belongs-to-relationship-improvements"
}
```

@bmac, @fivetanley, @igorT rolling back hasMany and hasOne relationships is a different beast and IMO a separate issue. 

To be clear I am not talking about the rolling back of related records changes, only the rolling back of the `foreign_key`.  The `foreign_key` is an attribute on the model there is no reason it should not be rolled back with every other attribute.

I don't get the argument that ember data is trying to work with non relational databases. The name `belongsTo` directly implies where the `foreign_key` lives. 

Please reconsider reopening this pull request.

**Comment by bmac** [comment]
I'll try to get feedback for this issue and https://github.com/emberjs/data/pull/2881 at the next ember data weekly meeting.

**Comment by frank06** [comment]
What's the progress with this and #2881 ?

**Comment by frunjik** [comment]
Whats is the status on this and how does it compare to: #4361 ?

**Comment by stevesims** [comment]
I was quite surprised to discover earlier today that if I have loaded up record A which is linked to record B via a `belongsTo` relationship, and I then null out that link in record A, that I currently have no way of knowing that record A is "dirty".  That seemed like a big omission.

I was even more surprised to discover that if I have made such a change that there's no way to rollback.

Seems like I may have to write some rather bodgy to work around this!

It would be very nice if this, and/or the functionality in #4361 could be prioritised for inclusion.

**Comment by TameBadger** [comment]
also commented on #4361, is there a place to see where/when the next "ember data weekly meeting" will occur ?

**Comment by arenoir** [comment]
@igorT see you at this ember meetup.  Merge this shiznet.

**Comment by matteodepalo** [comment]
@arenoir thanks for the PR! I've pulled it in my project and I'm using it, but I had to add a small fix to DS.Model because the dirtiness wasn't being reset when saving the record. What I've found is that the canonicalState is not set to the new value after save. It might be a problem in my app, but I wanted to share regardless to see if you have experienced the same issue.

```
DS.Model.reopen({
  save() {
    this._super(...arguments).then(() => {
      this.resetDirtiness();
    });
  },

  resetDirtiness() {
    this.eachRelationship((name, meta) => {
      if (meta.kind === 'belongsTo') {
        this._internalModel._relationships.get(name).isDirty = false;
      }
    });
  }
});
```

**Comment by leifdejong** [comment]
I don't know if this helps but I extended changedAttributes to also return changed relationships. I also included a snippet to commit without using the .save() method. 

```javascript
Model.reopen({

  /**
   * commit() saves changes locally without pushing to the server
   */
  commit() {
    this.get('_internalModel').send('willCommit');
    this.set('_internalModel._attributes', {});
    this.get('_internalModel').send('didCommit');
  },

  /**
   * changedAttributes() extends changedAttributes() to also return changed relationships
   */
  changedAttributes() {
    const attributes = this._super(...arguments);
    const relationships = {};

    // check relationships
    this.eachRelationship((name, meta) => {
      if (meta.kind === 'belongsTo') {
        if (this.get(`_data.${name}.id`) !== this.get(`${name}.id`)) {
          relationships[name] = [
            this.get(`_data.${name}.id`),
            this.get(`${name}.id`),
          ];
        }
      }
    });

    return Ember.merge(attributes, relationships);
  },
});
```

**Comment by JackEllis** [comment]
@arenoir @matteodepalo Thanks very much for your posts here! Would you two mind if I had a play around and created an addon out of your code? I don't want other people having to search a series of github tickets in the future.

**Comment by workmanw** [comment]
I would really like to see this land. 

I can't speak to the specific implementation in this PR, but I've been using ember-data for years and this is the single biggest frustration I've had. I've seen countless bugs in our application stem from trying to rollback or dirty track a belongsTo relationship. I just watched a coworker spend over an hour working to debug an issue that turned out to be caused by inadvertently checking `hasDirtyAttributes` when the user changed a `belongsTo` value.

**Comment by ldong** [comment]
Any updates? This ought be merged.

**Comment by xomaczar** [comment]
Any news on the before mentioned RFC?

**Comment by abhilashlr** [comment]
👍  Any news on the RFC? Would love to see this rollback for belongsTo resolved.

**Comment by erkie** [comment]
How can we help get this issue fixed? What's the blocker?

**Comment by malatin3** [comment]
This is a huge pain point with ember data for us. Would love to see this merged.

**Comment by XaserAcheron** [comment]
At risk of being "that guy": I'm struggling through this at present, and it feels a lot like I drove a car into a parking space only to find out the next day that the car can't reverse.

I get that this is a hard feature to add, but I'm un-thrilled about the radio silence as of late.

**Comment by erkie** [comment]
One solution for certain cases is to use [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments).

I found that to implement arrays of plain objects or primitive types I was modeling them as ember-data relationships, when I didn't really want or need the overhead of the ember-data object.

**Comment by broerse** [comment]
Should this be called `isDirty` ? Perhaps more logical: 

`hasDirtyFields: Ember.computed.or('hasDirtyAttributes', 'hasDirtyRelationships')`

**Comment by workmanw** [comment]
This was marked "Needs Team Discussion" nearly two years ago. Was there a discussion on this? Is there anything that can be shared from the core team about this? As a long time ember user, it's just down right frustrating to see PRs with a lot of support sit without any feedback.

**Comment by Ramblurr** [comment]
> I just watched a coworker spend over an hour working to debug an issue that turned out to be caused by inadvertently checking hasDirtyAttributes when the user changed a belongsTo value.

This exactly describes my afternoon. Incredibly frustrating!

**Comment by runspired** [comment]
@workmanw the short answer is that there have been many tried and failed attempts at resolving this by the core team. Discussions, spiked implementations, concepts.  Ultimately it comes down to this being one of the hardest concepts to solve generally because there is simply so much variation in API design (even tying to `json-api` spec doesn't solve this issue for the most part).

This was one of the first things I looked to "fix" when I began working on `ember-data` two years ago. It took me a few weeks to understand the full scope of the issue and quite obviously nothing ever came of that. It's a problem that seems simple at first and quickly becomes the most complex issue any ORM can possibly face.

The above said, over the past few years we've identified a few areas that if-improved would improve our ability to potentially, maybe, eventually rollback relationships.

- dirty both sides of the relationship
- determine new dirty-state when new relationship data comes in (requires changing our current diff, which needs to change anyway to resolve #4804 )
- improve documentation of the contract between adapter and store, and educate on available patterns

There's also a few ideas that still have merits but don't solve the problem the way they first appear to:

- single source of truth for relationships

And some ideas that just won't work due to API complexity

- in-flight relationship data

You'll maybe note that `in-flight` is in the "just wont work" category here. Ultimately this is the core reason why rollback has never successfully landed. Here's a simple fail scenario:

- A 1:1 B
- A sets B
- B saves (which in this API does save the new relationship)
- A rollback of B before B save completes
- B resolves with no new relationship info (APIs in the wild often will not)
- A:B linkage does not exist though it should

Ultimately, the store is incapable of storing in-flight state for relationships. However, adapters are well suited for this, and if we improve usage patterns in the request layer and improve our ability to correctly respond to changes in canonical state we will unlock the ability for users to implement relationship rollback locally as well.

Bear in mind, all of this discussion is **only** for the viewpoint that `rollback` and `dirty` tracking of relationships is for the `linkage`, not the state of the related records themselves.  That's a very different concept, and not one that rollback should cover on the record level.

**Comment by runspired** [comment]
Closing this in favor of addons like ember-data-changetracker and use of a RecordData based approach. That said improved relationship primitives are in the works for RecordData authors to make use of, and would include tracked changes for easier rollback and diffing.

**Pull request closed without merging**
