### PR TITLE
deprecate ActiveModelAdapter being bundled with core

### PR DESCRIPTION
**Pull request by fivetanley**

### CODE REVIEW

**Comment by wecc** [comment]
LGTM

**Comment by igorT** [comment]
Can someone setup active model stuff using initializers/container and not hit this deprecation?

**Comment by fivetanley** [comment]
yes. if you are using ember-cli it works. otherwise it should just work.

**Comment by fivetanley** [comment]
https://github.com/ember-data/active-model-adapter/blob/master/lib/globals.js

**Pull request merged**
