### PR TITLE
Pin ember-cached-decorator-polyfill version to 0.1.3 

### PR DESCRIPTION
**Pull request by igorT**
ember-cached-decorator-polyfill 0.1.4 fails with 
```
@ember-data/record-data: Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/model]) in -private/attr.js
@ember-data/record-data: Duplicate plugin/preset detected.
@ember-data/record-data: If you'd like to use two separate instances of a plugin,
@ember-data/record-data: they need separate names, e.g.
@ember-data/record-data:   plugins: [
@ember-data/record-data:     ['some-plugin', {}],
@ember-data/record-data:     ['some-plugin', {}, 'some unique name'],
@ember-data/record-data:   ]
@ember-data/record-data: Duplicates detected are:
@ember-data/record-data: [
@ember-data/record-data:   {
@ember-data/record-data:     "alias": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js",
@ember-data/record-data:     "dirname": "/home/runner/work/data/data/packages/record-data",
@ember-data/record-data:     "ownPass": false,
@ember-data/record-data:     "file": {
@ember-data/record-data:       "request": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js",
@ember-data/record-data:       "resolved": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js"
@ember-data/record-data:     }
@ember-data/record-data:   },
@ember-data/record-data:   {
@ember-data/record-data:     "alias": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js",
@ember-data/record-data:     "dirname": "/home/runner/work/data/data/packages/record-data",
@ember-data/record-data:     "ownPass": false,
@ember-data/record-data:     "file": {
@ember-data/record-data:       "request": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js",
@ember-data/record-data:       "resolved": "/home/runner/work/data/data/node_modules/ember-cached-decorator-polyfill/lib/transpile-modules.js"
@ember-data/record-data:     }
@ember-data/record-data:   }
@ember-data/record-data: ]
```

### CODE REVIEW

**Comment by dcyriller** [comment]
@igorT have you seen https://github.com/emberjs/data/pull/7599?

**Comment by igorT** [comment]
Yeah but 0.1.4 is currently broken https://github.com/ember-polyfills/ember-cached-decorator-polyfill/issues/94

**Comment by dcyriller** [comment]
Prior to v0.1.4, ember-cached-decorator-polyfill was not registering its Babel plugin for addons. This was most likely a bug. The bug being fixed, the polyfill is now registered twice in ember-data? Indeed, the Babel plugin is also manually registered in ember-data. This should be solved by https://github.com/emberjs/data/pull/7599.

**Review by dcyriller — APPROVED** [review]

**Comment by igorT** [comment]
Closing in favor of https://github.com/emberjs/data/pull/7639

**Pull request closed without merging**
