### PR TITLE
Simplify Adapter#serialize by using snapshot.serialize() since they d…

### PR DESCRIPTION
**Pull request by bmac**
…uplicate the same logic

cc @wecc

### CODE REVIEW

**Comment by sly7-7** [comment]
After a quick search about adapter.serialize, it seems like it's never called in the repository. Maybe we could even deprecate it and remove it for 3.0 ?

**Comment by bmac** [comment]
That sounds good to me @sly7-7. I think the same thing could happen for `store#serialize`

**Comment by sly7-7** [comment]
@bmac I just wonder what we want as a public api for serializing a record. Do we want only keep `record.serialize(options)` ?

**Comment by bmac** [comment]
I think `record.serialize(options)` and `snapshot.serialize(options)` is the way to go.

**Pull request merged**
