### PR TITLE
Revert "Fix nightly run"

### PR DESCRIPTION
**Pull request by Cunero-Lang**
Reverts emberjs/data#7094

### CODE REVIEW

**Comment by rwjblue** [comment]
Is there some context here? Why is this being reverted?

**Comment by Cunero-Lang** [comment]
Porque si funciona. Todo método requiere comprobaciones. Porque la info de una rama  y otra rama,  no son tan iguales.

**Comment by runspired** [comment]
Closing this as I would prefer to keep the fix unless that fix wasn't enough, in which case lets determine the correct fix.

**Comment by Cunero-Lang** [comment]
Hey @runspired why (?) I need it running two days. Tomorrows night is other history and components is full for us... please, Dont "snif" here.

**Pull request closed without merging**
