### PR TITLE
remove usage and deprecate InternalModel's type property

### PR DESCRIPTION
**Pull request by sly7-7**
I hope this moves to the right direction. (#4584)
I wonder if we would do the same for the Snapshot and RecordArray classes

cc/ @runspired

### CODE REVIEW

**Comment by stefanpenner** [comment]
oops didn't notice this, these should be fixed up. If any are missing please reopen/resubmit

**Comment by sly7-7** [comment]
@stefanpenner No worries, I will check if any are missing

**Comment by sly7-7** [comment]
@stefanpenner I just checked, if we still want to deprecate internalModel.type, there is one place missing: https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/create.js#L18

I did not find any other missing replacement, even if for some label, `internalModel.modelClass` was replaced by `internalModel.modelName`, but I assume this is merely the the same thing for labels.

Just let me now if you want me to resubmit a PR deprecating and removing `internalModel.type`

**Comment by stefanpenner** [comment]
I'm not sure how to remove the one you linked to easily

**Comment by sly7-7** [comment]
why not just using [internalModel.modelClass](https://github.com/emberjs/data/blob/master/addon/-private/system/model/internal-model.js#L158) ?

**Pull request closed without merging**
