### PR TITLE
[DOC beta] Use findRecord syntax in unloadRecord documentation

### PR DESCRIPTION
**Pull request by jeffreybiles**
Just a small update to the new syntax.

### CODE REVIEW

**Comment by wecc** [comment]
LGTM, thanks! Would you be able to prefix the commit message with `[DOC beta]`?

**Comment by jeffreybiles** [comment]
Done :)

**Comment by wecc** [comment]
@fivetanley :two: :fast_forward: :four: @wecc

**Comment by fivetanley** [comment]
2 left my email notifications on 2 furious

**Pull request merged**
