### PR TITLE
add .iml to gitignore

### PR DESCRIPTION
**Pull request by svox1**

### CODE REVIEW

**Comment by igorT** [comment]
What is .iml?

**Comment by svox1** [comment]
Oh sorry. Its a Module Library file from IntelliJ IDEA. 
From the Jetbrains website:
The library classes are visible only in this module and the library information is recorded in the module *.iml file.

**Comment by stefanpenner** [comment]
@svox1 this is really something that should be added to your system wide gitignore

**Comment by svox1** [comment]
@stefanpenner ok. There was also the `.idea` entry, so thats why I`am adding the *.iml. Its booth from IntelliJ IDEA.

**Pull request merged**
