### PR TITLE
changelog: Switch to using lerna-changelog

### PR DESCRIPTION
**Pull request by dcyriller**
### Description

This PR implements the item `move to lerna changelog from custom solution` referenced in https://github.com/emberjs/data/issues/6103

The goal is to simplify / standardize the changelog generation around an external solution. It allows to remove some infrastructure code.

The RELEASE notes are taken and adapted from [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint).

### Github UI Labels

I configured lerna-changelog to read ember-data labels: `changelog:*`. This configuration would require making two changes to ember-data Github labels: you would have to create a `changelog:breaking` label for breaking changes and remove the `changelog:security` label (it has been used only once for a dependabot dep ugprade).

### Giving it a try

Checkout the branch locally, install deps and run: `yarn lerna-changelog --from=3.13.3`.

Note: you might have to add a token to fetch from Github API: https://github.com/lerna/lerna-changelog#github-token

### Caveat

It would genereate a CHANGELOG based on Github labels only, meaning that it would not reference any commit anymore. Previously, the changelog script used to also generate CHANGELOG entries based on commit prefixes ([FEAT] / [CHORE] for instance). But this is not how lerna-changelog works and porting the feature there seems unlikely. Is it okay to abandon the feature?

### CODE REVIEW

**Comment by rwjblue** [comment]
@dcyriller - Might want to remove `bin/changelog` too though.

**Comment by dcyriller** [comment]
indeed, it should be gone now

**Review by snewcomer — APPROVED** [review]
This would be very helpful.  I'm in favor of it.  If you have time, possible we could resolve conflicts and then we can talk about it at the weekly meeting.

**Comment by dcyriller** [comment]
@snewcomer I rebased and resolved the conflicts. Your meeting is pretty late for me (11pm if I remember well). But if you need me to explain the PR, feel free to reach out, I could do it once.

Also, please don't forget that this PR would require making two changes to the repository's labels:
- you would have to create a `changelog:breaking` label for breaking changes
- and remove the `changelog:security` label (it has been used only once for a dependabot dep ugprade).

**Comment by runspired** [comment]
@rwjblue was this ever discussed? I didn't see anything in the meeting notes from last fall.

**Review by runspired — APPROVED** [review]

**Review by runspired — APPROVED** [review]

**Pull request merged**
