### PR TITLE
Add tests for urlFor methods

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves #2966

### CODE REVIEW

**Comment by thejameskyle** [comment]
derp, I meant this resolves #2986

**Comment by igorT** [comment]
restarted travis

**Comment by stefanpenner** [comment]
for the first time in history, appveyor passed but travis failed ;P

**Comment by igorT** [comment]
I was just about to screenshot that :)

**Comment by igorT** [comment]
Thanks!

**Pull request merged**
