### PR TITLE
[DOC beta] Fix typo in inline doc. of normalizeResponse

### PR DESCRIPTION
**Pull request by balinterdi**

### CODE REVIEW

**Comment by pangratz** [comment]
köszönet @balinterdi! Can you prefix with `[DOC beta]`? Unfortunately this is not clear from the `CONTRIBUTING.md` and this definitely needs to be updated...

**Comment by balinterdi** [comment]
Sure, I've just added the [DOC beta] prefix to both this PR and the commit message.

**Comment by pangratz** [comment]
Thank you kindly! :rocket:

**Comment by balinterdi** [comment]
Gerne!

**Pull request merged**
