### PR TITLE
Allow errors on arbitrary properties, not just defined attributes or relationships.

### PR DESCRIPTION
**Pull request by alexspeller**
Addresses #1877

@tchak @igorT ping

### CODE REVIEW

**Comment by ahacking** [comment]
IMO this should be merged.

Since PR #2392 has been merged, error payload processing is now a serializer concern. There should be no reason not to include all errors that the serializer has sanctioned.

ping @igorT, @alexspeller, @tchak

**Comment by alexspeller** [comment]
If this will be merged I will update the PR. But if it will be ignored for another 8 months there is no point as it will have to be rebased again. So if someone on the core team does want this, please ping me when you are ready so that I can make the changes.

**Comment by tchak** [comment]
@igorT @alexspeller I am :+1: on merging this

**Comment by alexspeller** [comment]
Awesome, I will rebase shortly

**Comment by alexspeller** [comment]
@tchak rebased and tests all passing :)

**Comment by alexspeller** [comment]
@tchak @igorT ping

**Comment by bjornstar** [comment]
Can this PR get some love?

**Pull request merged**
