### PR TITLE
Add modelClass argument to JSONSerializer.extractId

### PR DESCRIPTION
**Pull request by pdud**
This should take care of #3471 :)

### CODE REVIEW

**Comment by wecc** [comment]
I'm :+1: this change but I suspect it's be a breaking change for people already overriding `extractId`?

**Comment by pdud** [comment]
Yes it would be a breaking change for those overriding `extractId`.

It is possible to not make it breaking by making the argument order `resourceHash` then `modelClass`.
Doing that would be the opposite to the other extract methods.

https://github.com/pdud/data/blob/extract-id/packages/ember-data/lib/serializers/json-api-serializer.js#L193

**Comment by bmac** [comment]
@wecc was `extractId` introduced in 1.13? Also it currently does not show up in the API docs because the doc block doesn't start with `/**`.

**Comment by wecc** [comment]
LGTM

**Comment by wecc** [comment]
Thanks @pdud!

**Comment by wecc** [comment]
@bmac ping `release`

**Comment by pdud** [comment]
Glad to help out :) Thanks for marking issues as Good for New Contributors!

**Pull request merged**
