### PR TITLE
[BUGFIX] fix deprecation for store entry methods

### PR DESCRIPTION
**Pull request by runspired**

### CODE REVIEW

**Comment by Gaurav0** [comment]
@runspired Is it possible to backport this to Ember Data 3.4 LTS?

**Comment by runspired** [comment]
@Gaurav0 this already was.

**Comment by ELepolt** [comment]
Sorry, I came across this thread trying to track this down. I might not be following correctly, but isn't this the line that is currently in 3.4 LTS: https://github.com/emberjs/data/blob/lts-3-4/addon/-private/system/store.js#L3428

**Comment by Gaurav0** [comment]
I'm still seeing the deprecation warning in 3.4.4

**Comment by runspired** [comment]
@Gaurav0 you should see this deprecation in 3.4.4 if you are hitting it for correct reasons, this fix was to ensure that folks didn't hit it for incorrect reasons.

**Comment by Gaurav0** [comment]
@runspired I am hitting it during teardown in application tests and in rendering tests in which data is added to the store.

**Pull request merged**
