### PR TITLE
If using {{input value=date}},  should got the right date instead of null.

### PR DESCRIPTION
**Pull request by Eric-Guo**
To avoid writing below code in Ember app.

```javascript
export default Ember.Component.extend({
  actions: {
    save: function(item) {
      let self = this;
      item.set('start', new Date(item.get('start'))); # not necessary
      item.set('end', new Date(item.get('end')));   # after apply this commit.
      item.save().then(function() {
        self.set('isEditing', false);
      });
    }
  }
});
```

### CODE REVIEW

**Comment by Eric-Guo** [comment]
failed in `npm run-script test:canary` not my fail, maybe it's just not right time...

**Comment by Eric-Guo** [comment]
@bmac can now accept my first PR?

**Comment by bmac** [comment]
Hi @Eric-Guo. I agree it's frustrating not being able to bind a date attribute directly to a date input. However, I'm not sure that changing the date transform to serialize strings is the best solution to this problem. 

While it is a simple fix, it means a date attribute can contain 2 types of values (strings and date object). This can cause problems with code that consumes the date attribute (like computed properties or template helpers) as it now must work with both strings and date objects.

**Comment by Eric-Guo** [comment]
Sounds reasonable, thanks.

**Pull request closed without merging**
