### PR TITLE
Replace Ember.String.{pluralize,singularize} with ember-inflector imports

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by stefanpenner** [comment]
we just fixed our tests, @locks mind rebasing? That way we know this actually works against all supported versions of ember.

**Comment by locks** [comment]
🏓

**Comment by Turbo87** [comment]
@rwjblue @stefanpenner can we backport this to beta to unblock https://github.com/emberjs/ember-inflector/pull/131?

**Comment by Turbo87** [comment]
@locks I think you missed https://github.com/emberjs/data/blob/master/tests/integration/serializers/rest-serializer-test.js#L78

**Comment by locks** [comment]
@Turbo87 thank you https://github.com/emberjs/data/pull/5141

**Pull request merged**
