### PR TITLE
Add es5-sham warning for IE8 support

### PR DESCRIPTION
**Pull request by trabus**
See [#2553]

### CODE REVIEW

**Comment by trabus** [comment]
Sorry no, I haven't had time to investigate further. We have it working with the ES5 shim, so it wasn't as high of a priority. I may have a little time next week, and we'll be upgrading our app to 1.9 as well.

**Comment by trabus** [comment]
I finally tracked the issue down, and have determined that it was a utility that we were using that called Array.isArray(). Sorry for any confusion this has caused, IE8 is near impossible to debug, and I wasn't able to see what specifically was causing the error.

Running Ember 1.9.1 and Ember Data 1.0.0-beta.14 without the ES5-shim and all is well on IE8.

**Comment by bmac** [comment]
Looks good to me. @fivetanley can you review and merge?

**Comment by fivetanley** [comment]
thanks!

**Pull request merged**
