### PR TITLE
Use JSON-API adapter and serializer in blueprints

### PR DESCRIPTION
**Pull request by pangratz**
This addresses ember-cli/ember-cli#4787.

### CODE REVIEW

**Comment by bmac** [comment]
@pangratz do you mind amending this commit message to start with [BUGFIX beta]?

**Comment by pangratz** [comment]
Sure thing.

**Comment by igorT** [comment]
Looks good. @pangratz if you have time, it would be awesome to do the thing where it uses applicationSerializer if there is one.

**Comment by igorT** [comment]
@bmac says they already do that, so nevermind me if they do

**Comment by pangratz** [comment]
> @bmac says they already do that, so nevermind me if they do

If I am reading the current blueprints correctly, this is not the case :fearful:. I've opened a followup PR #4023 which addresses this...

**Pull request merged**
