### PR TITLE
Added tests for polymorphic find

### PR DESCRIPTION
**Pull request by mmoonport**
Added new tests for polymorphic find at the request of @igorT. This implements testing the find by calling a base call that is of a polymorphic type and retrieving the appropriate model type from the store.

### CODE REVIEW

**Comment by igorT** [comment]
@mmoonport thanks! We need a bit of design work around how `findAll` and `all` work with this, about what happens when you do `all(superclass)` whether it includes child classes, so might be a bit more time before we finish

**Comment by mmoonport** [comment]
@igorT no problem. If there is anything I can do to help speed this along let me know.

**Comment by mmoonport** [comment]
@igorT any update on this issue?

**Comment by igorT** [comment]
Waiting on https://github.com/emberjs/rfcs/pull/67

**Comment by bmac** [comment]
I'm going to close this pr since the `references` was merged into master a long time ago.

**Pull request closed without merging**
