### PR TITLE
Add a real error message for attempts to manipulate a recordArray and…

### PR DESCRIPTION
**Pull request by ckl1989**
… prevent it from trying to perform manipulation #4513 

When a findAll() is called on the store, a recordArray is returned. If a user were to try and manipulate this recordArray with something like a pushObject() or reverseObjects(), a TypeError will be thrown for one of the internal models. See #4513.

This error, while warranted, is a little misleading to the actual problem. There isn't much documentation to describe that RecordArrays are not mutable, leading to hours of frustration for beginners to figure out why such a simple task on an apparently ember Array type is not "working".   

AdapterPopulatedRecordArray and FilteredRecordArray all have prevent attempts at manipulation and have descriptive error messages. I think RecordArray should also have it,

### CODE REVIEW

**Comment by bmac** [comment]
Overall I'm 👍 for this change as it provides a much better error message then exists today. 

@fivetanley has a similar change in pr https://github.com/emberjs/data/pull/4045, but I don't think that prevents us from landing this pr now.

@pangratz, @fivetanley what are your thoughts?

**Comment by pangratz** [comment]
Basically looks good to me, thanks @ckl1989 🚀 

One minor tiny nitpick: what do you think of moving the test to the existing [`tests/unit/record-array-test.js`](https://github.com/emberjs/data/blob/master/tests/unit/record-array-test.js) and using a "real" `type` (`Person` is already available in the tests), so we can make sure that the thrown error message contains the correct type information (in the current test the type is mocked). I would also tend to try to modify the result of `store.peekAll()` and not use the `DS.RecordArray` directly. What do you think?

**Comment by ckl1989** [comment]
@pablobm @bmac Thank you for your feedback! I've added your change suggestions. They make a lot of sense. Currently I've modeled my test's expected error message after the one in the adapter-populated-record-array. Did you want it more specific? (instead of just showing "subclass of DS.Model", actually show "person").

I'm a junior ember developer and it really means a lot to have this validation after all the uncertain research I had been doing about this issue. Thank you again. Let me know if there's are any other change requests.

**Comment by pangratz** [comment]
Thanks for the update @ckl1989.

Hmm, it seems that the `toString` functionality is somehow not setup as I though it would be, when using the `setupStore` utility. But `<subclass of DS.Model>` showing up instead of the actual `modelName` is also kind of expected [another test](https://github.com/emberjs/data/blob/v2.7.0/tests/unit/model-test.js#L204).

Resolving this (if desired at all), is out of scope for this PR, so I would say we go ahead and merge. @bmac @fivetanley thoughts?

**Comment by ckl1989** [comment]
bump

**Comment by fivetanley** [comment]
@ckl1989 Can you update the message to tell them to use `toArray` instead?

**Comment by ckl1989** [comment]
@bmac @pangratz @fivetanley 

I've updated the error message and locally built and ran the tests on my machine. However AppVeyor is failing on the canary tests but I'm not really understanding the logs. Can you advise? Thanks!

**Comment by bmac** [comment]
Thanks @ckl1989.

**Pull request merged**
