### PR TITLE
Add a way to pass options to an adapter (rebase)

### PR DESCRIPTION
**Pull request by HeroicEric**
rebasing https://github.com/emberjs/data/pull/3278

### CODE REVIEW

**Comment by igorT** [comment]
Maybe we should put the options on the snapshot, otherwise not sure how coalescing will work

**Comment by bmac** [comment]
Would options go on the snapshot and be passed as an argument into the adapter's `find` method?

**Comment by igorT** [comment]
yes, see also the discussion in slack

**Comment by HeroicEric** [comment]
@bmac should I close this now since I see https://github.com/emberjs/data/commit/059ec88cbc3a71a698f7a8952e2e8022d927c36e?

**Comment by bmac** [comment]
yes, thanks

**Pull request closed without merging**
