### PR TITLE
WIP Allow users to opt-in to use ember-ajax

### PR DESCRIPTION
**Pull request by taras**
For context, please refer to #4175

### CODE REVIEW

**Comment by bmac** [comment]
@taras Do you mind wrapping this change in a feature flag?

**Comment by bmac** [comment]
ping @taras. Do you have any time to work on this?

**Comment by yads** [comment]
What would a good name for this feature be?

**Comment by bmac** [comment]
Something along the lines of `ds-ember-ajax-support`.

**Comment by yads** [comment]
@bmac @taras see #4430

**Comment by stefanpenner** [comment]
closing in-favor of feature flaged variant: https://github.com/emberjs/data/pull/4430

**Pull request closed without merging**
