### PR TITLE
ember-data should provide its blueprints

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x]  add blueprints
- [x] test blueprints

### CODE REVIEW

**Comment by knownasilya** [comment]
Nice. Glad this is a thing.

**Comment by rwjblue** [comment]
@stefanpenner - Mind if I pick this up, rebase, and whatnot?

**Comment by stefanpenner** [comment]
@rwjblue would appreciate that thanks:)

**Comment by rwjblue** [comment]
OK, rebased and passing.  Do we want to block this on pulling in `ember-cli-blueprint-test-helpers` and adding tests here?

Also, if we do, does anyone object to using `mocha` for the node-land tests? 

Sample test using `ember-cli-blueprint-test-helpers` + `mocha`: https://github.com/dockyard/ember-suave/blob/master/tests/blueprint-test.js

**Comment by rwjblue** [comment]
Added tests for blueprints.

**Comment by stefanpenner** [comment]
> Do we want to block this on pulling in ember-cli-blueprint-test-helpers and adding tests here?

Yes, I believe we need to get the tests integrated (or we will just troll everyone)

> Also, if we do, does anyone object to using mocha for the node-land tests?

no objections

**Comment by rwjblue** [comment]
@stefanpenner - Ya, I pulled them in already.  Still tweaking to get them all passing/happy.

**Comment by rwjblue** [comment]
OK, I beleive this is ready for a review.  I updated the blueprints from current ember-cli master, and ensured that tests were in place for each blueprint.

**Comment by stefanpenner** [comment]
SGTM, we likely should get @trabus to take a look aswell

**Comment by stefanpenner** [comment]
we may want to be sure the windows build passes, now that the node side is actually important...

**Comment by trabus** [comment]
I have all my extracted tests here in this branch: https://github.com/trabus/ember-cli-legacy-blueprints/blob/blueprints/

I've got the addon, dummy, and pod tests as well. It should be noted that I used `blueprint-nodetest.js` so it could be ignored with an `.npmrc` file. You can generate blueprint tests with the blueprint test helpers, and installing should generate the dotfile and a runner as well.

Here's the adapter tests for example: https://github.com/trabus/ember-cli-legacy-blueprints/blob/blueprints/blueprints/adapter/blueprint-nodetest.js

**Comment by trabus** [comment]
I'm talking about the default blueprint here: https://github.com/ember-cli/ember-cli-blueprint-test-helpers/tree/master/blueprints/ember-cli-blueprint-test-helpers

**Comment by rwjblue** [comment]
Thanks @trabus, I'll get this updated (stealing all of your hard work :dancers:).

**Comment by trabus** [comment]
>  (stealing all of your hard work :dancers:).

That was my intent from the get-go. :)

**Comment by trabus** [comment]
@rwjblue @stefanpenner do we want to go with using the blueprint name in the test and putting the them in `node-tests/blueprints/`?

**Comment by rwjblue** [comment]
@trabus - I'm playing with it the way you have it first (test co located with the blueprint itself).

**Comment by trabus** [comment]
@rwjblue I'm really okay either way. Honestly, the `node-tests` folder makes sense to me, and might be a good format to align with.

**Comment by stefanpenner** [comment]
> node-tests folder makes sense to me, and might be a good format to align with.
> Add more commits by pushing to the addonified branch on emberjs/data.

:+1:

**Comment by trabus** [comment]
I'll get the blueprint fixed then, and will move the blueprint-tests in legacy-blueprints to the node-tests folder.

**Comment by rwjblue** [comment]
Updated the infrastructure to use the base setup provided by ember-cli-blueprint-test@0.6.0 (using `node-test/` folder as mentioned by @trabus above).  Will update the actual tests tomorrow (I believe @trabus is updating them in the ember-cli-legacy-blueprints package so I'll just copy-pasta after that is done).

**Comment by bmac** [comment]
@rwjblue what is the status of this pr? I am planning on doing another 2.3 beta release today and wanted to see if this was ready to pull in.

**Comment by stefanpenner** [comment]
I believe it is in working order, but @rwjblue should confirm as he has been helping push it to completion.

**Comment by rwjblue** [comment]
Ya, this is good to land in next beta. I will continue working in additional PR's to flesh out the blueprint tests a bit more.

**Comment by bmac** [comment]
Thanks for all the work @stefanpenner and @rwjblue.

**Pull request merged**
