### PR TITLE
fix(blueprints): remove second string argument from transform tests

### LINKED ISSUE #5656: transform-test blueprint uses qunit module wrong
Hi,
the current transform-test generates a qunit setup that works but isn't actually expected to work.

`module` [is defined as](https://api.qunitjs.com/QUnit/module) `QUnit.module( name [, hooks] [, nested ] )`

The generated module call looks like this:
`module('transform:<%= dasherizedModuleName %>', '<%= friendlyTestDescription %>', function(hooks) {`

This causes qunit to parse the friendlyTestDescription into its test environment:

Another indicator that this is probably a bug is that all other blueprints don't set the second argument as a string:

I'll open a PR soon to fix this

### PR DESCRIPTION
**Pull request by makepanic**
fixes #5656

### CODE REVIEW

**Comment by makepanic** [comment]
I just noticed that yarn updated the yarn.lock with `integrity`. Should i remove that from the PR?

**Comment by runspired** [comment]
@makepanic yeah, please remove the yarn.lock change. Otherwise LGTM

**Comment by makepanic** [comment]
I've removed the yarn.lock changes

**Comment by runspired** [comment]
Thanks @makepanic !

**Pull request merged**
