### PR TITLE
Remove Fixture Adapter

### PR DESCRIPTION
**Pull request by greyhwndz**
@bmac: Would be glad to hear some feedback regarding this PR. Thanks!

### CODE REVIEW

**Comment by bmac** [comment]
Could you also remove this file? https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/fixture-adapter.js

**Comment by greyhwndz** [comment]
@bmac: Done.

**Comment by bmac** [comment]
Oops, looks like the fixture adapter also needs to be emoved from this file: https://github.com/emberjs/data/blob/7b2c70d5e454a485eae4d64c7cdabfa020208b9d/packages/ember-data/lib/adapters.js

**Comment by greyhwndz** [comment]
@bmac: Just finished removing the references to FixtureAdapter in lib/adapter.js

**Comment by greyhwndz** [comment]
@bmac: This should address issue #3691

**Pull request merged**
