### PR TITLE
[PERF] Ajax should join an existing run if one exists

### PR DESCRIPTION
**Pull request by chadhietala**

### CODE REVIEW

**Comment by fivetanley** [comment]
So Ember has its own instance of Backburner.... I'm not sure what we should be using here. This is probably right, but I don't know enough about why we have our own instance.

cc @igorT @stefanpenner

**Comment by runspired** [comment]
There's a separate instance? ime ED has it's own queues, but those are added to the same instance.  Or at least they were when I poked around a while back, probably around beta 18.

**Comment by fivetanley** [comment]
https://github.com/emberjs/data/blob/master/addon/system/store.js#L220

**Comment by krisselden** [comment]
@fivetanley this comes into play if you have cached or server side rendered response you fullfill the ajax with and already have a run loop.

**Comment by krisselden** [comment]
@chadhietala can you flatten?

**Comment by chadhietala** [comment]
@krisselden squashed.

**Comment by stefanpenner** [comment]
LGTM.

For those reading along ofcourse for most people this doesn't make a difference, But if they happen to batch multiple XHR at a lower layer then this, they can easily now wrap that base in a run, batching these higher level one.

**Comment by stefanpenner** [comment]
@fivetanley not to worry, that should not matter, the ED bb should stay the way it is. (at least for now)

@runspired it has its own bb instance, and the queues are not shared between instances. the aim was avoid plan interference of two different interleaving priority queues.

The ember bb queue, can run a task which triggers the ED queue to be added to (maybe several times). At which time, the ED queue must flush entirely. This ensures the various multi-phase ED relationship synching steps can reach a consistent state before releasing back to ambient flush.

In theory with some changes to BB this could have been supported with 1 BB instance, but the current approach required no extra BB work, keeping the complexity down, and was semantically the same.

**Comment by bmac** [comment]
Thanks @chadhietala.

**Pull request merged**
