### PR TITLE
Fix failing delete-record-test

### PR DESCRIPTION
**Pull request by Bajena**

### CODE REVIEW

**Comment by Bajena** [comment]
The AppVeyor build is failing because of the execution time is exceeded. How can we fix this?

**Comment by sly7-7** [comment]
Seems like @stefanpenner did the same thing in #5030

**Comment by stefanpenner** [comment]
@Bajena oh, I didn't even see this! Good job!

**Comment by Bajena** [comment]
@stefanpenner no worries ;)

**Pull request closed without merging**
