### PR TITLE
[CLEANUP beta] Linter changes for addon, addon/adapters and addon/serializers

### PR DESCRIPTION
**Pull request by pete-the-pete**
Minor clean up for linter issues.

### CODE REVIEW

**Comment by bmac** [comment]
Hi @pete-the-pete. Thanks for this pr. Would you be opposed to making some changes so `let` is preferred over `const`? I believe this help bring Ember Data's coding conventions in line with the conventions used it Ember.

I believe Ember follows a convention of "liberally-let" per madhatted.com/2016/1/25/let-it-be and only allows `const` in module scope.

**Comment by pete-the-pete** [comment]
Sure, i'll update soon.  Is it worth it to make the actual eslintrc more similar?

https://github.com/emberjs/data/blob/master/.eslintrc.js vs https://github.com/emberjs/ember.js/blob/master/.eslintrc.js

**Comment by bmac** [comment]
making the .eslintrc.js more similar sounds like a good idea. 👍

**Comment by bmac** [comment]
Thanks @pete-the-pete.

**Pull request merged**
