### PR TITLE
Fix Typos in Documentation for DS.Adapter

### PR DESCRIPTION
**Pull request by heathharrelson**
Fix minor typos in the documentation comments for `DS.Adapter`:

* "chached" -> "cached"
* "form" -> "from"

### CODE REVIEW

**Comment by wecc** [comment]
Looks good! Can you prefix the commit with [DOC beta]?

**Comment by heathharrelson** [comment]
@wecc I'm happy to change whatever's necessary. What exactly should I prefix with [DOC beta]? The PR title, the commit message ... ?

**Comment by wecc** [comment]
The commit message :+1:

**Comment by heathharrelson** [comment]
Okay, updated the commit message.

**Comment by wecc** [comment]
Thank you!

**Pull request merged**
