### PR TITLE
Rename error attribute

### PR DESCRIPTION
**Pull request by tchak**
cc @bmac @igorT

### CODE REVIEW

**Comment by bmac** [comment]
Code looks good to me. Do we need to define a deprecation for the old `error` property?

**Comment by bmac** [comment]
Also @tchak do you mind prefacing the commits with [BUGFIX release] so we can make sure to cherry-pick the commits over to the 1.13 branch?

**Comment by tchak** [comment]
@bmac renaming is done

**Comment by bmac** [comment]
Thanks @tchak

**Pull request merged**
