### PR TITLE
Fixing typo that causes Ember-Data v1.13.10 to crash with Ember v2.0.

### PR DESCRIPTION
**Pull request by workmanw**

### CODE REVIEW

**Comment by bmac** [comment]
Thanks for catching this @workmanw. Looking into the build failure now.

**Comment by workmanw** [comment]
Happy to help :) 

Let me know if there is anything else I can do to kick it along.

**Comment by stefanpenner** [comment]
ROFL, `prorotype` (i can laugh because Its my mistake)

**Comment by workmanw** [comment]
@stefanpenner @bmac At first I was scratching my head at how that even passed the tests, but because they're run against Ember 1.13, it was just falling back to the `Ember.ArrayPolyfills`.

**Comment by bmac** [comment]
Build should be fixed. @workmanw do you mind rebasing your pr now?

**Comment by workmanw** [comment]
Done :beers:

**Comment by bmac** [comment]
Thanks @workmanw.

**Pull request merged**
