### PR TITLE
failing test for reference when id is procided

### PR DESCRIPTION
**Pull request by luxferresum**
This is a failing test for #5134.

This is my first Contribution to ember-data. If I should change something please tell me!

### CODE REVIEW

**Comment by luxferresum** [comment]
This seems to be fixed on master and `2.16`. I haven't checked other version. I will close the issue but leave this open because I think it would be good to have the test as regression test.

**Comment by luxferresum** [comment]
Is anything holding this back?

**Comment by bmac** [comment]
Thanks for the ping @luxferresum. I just re-trigger the travis build. If it passes again I will merge.

**Comment by bmac** [comment]
Thanks @luxferresum.

**Pull request merged**
