### PR TITLE
Backport @babel/plugin-transform-block-scoping fix to 3.8.0

### PR DESCRIPTION
**Pull request by erichuang310**
Already fixed on master and now backporting to 3.8

Original issue: https://github.com/emberjs/data/issues/6421

### CODE REVIEW

**Comment by runspired** [comment]
@erichuang310 thanks! any reason this is still a draft?

**Comment by runspired** [comment]
The CI issue here appears to be that we don't force CI to use (or somehow avoid CI using) our preferred checked-in version of yarn, so it downloads yarn 1.19 which has a cache integrity issue.

**Comment by runspired** [comment]
Assigning @HeroicEric to get 3.8 cleaned up so that we can land this.

**Comment by igorT** [comment]
Hi @erichuang310, thanks for the backport! Your yarn lock file kept a reference to internal LinkedIn artifactory. I cleaned that up and PRd it as https://github.com/emberjs/data/pull/6782 but I kept you as the author of the commit

**Comment by erichuang310** [comment]
Sweet! Thanks for the update :)

**Pull request closed without merging**
