### PR TITLE
install ember-cli-yuidoc addon

### LINKED ISSUE #5483: Invalid link for code location on api docs
image

Url: https://www.emberjs.com/api/ember-data/release/classes/DS.JSONSerializer/properties

It is only an example, The `DEFINED IN` link is invalid in all the page I encountered.

### PR DESCRIPTION
**Pull request by hakilebara**
Install [ember-cli-yuidoc](https://github.com/cibernox/ember-cli-yuidoc) to match the way docs are generated on ember.js
This aims to fix #5483

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
1. Please match the details in https://github.com/emberjs/data/blob/master/lib/yuidoc.js & ensure that its enabled only on production (https://github.com/cibernox/ember-cli-yuidoc#environment-specific-generation)
2. Remove the old references to broccoli yuidoc https://github.com/emberjs/data/search?q=yuidoc&unscoped_q=yuidoc
3. Add `yarn docs --environment=production` to https://github.com/emberjs/data/blob/master/.travis.yml#L71

**Comment by hakilebara** [comment]
> Please match the details in https://github.com/emberjs/data/blob/master/lib/yuidoc.js 

I don't think the `version` and `logo` attributes are needed.

> ensure that its enabled only on production (https://github.com/cibernox/ember-cli yuidoc#environment-specific-generation)

done


> Remove the old references to broccoli yuidoc

done


> Add yarn docs --environment=production to https://github.com/emberjs/data/blob/master/.travis.yml#L71

no need with the yuidoc.json `enabledEnvironments` option

**Comment by runspired** [comment]
Provided folks from the learning team confirm this is the right step (I don't know much about the YUI docs pipeline => ember docs site) I am 👍 to merge.

cc @locks @sivakumar-kailasam

**Comment by sivakumar-kailasam** [comment]
I haven't had the chance to try this locally but the diff looked right

**Comment by sivakumar-kailasam** [comment]
Tried using this PR on my machine & the output looks good.

@hakilebara I saw some differences when i ran `yarn` on your branch, can you check if you're experiencing the same?

**Comment by sivakumar-kailasam** [comment]
@runspired good to merge now

**Comment by runspired** [comment]
@sivakumar-kailasam @hakilebara thank you both!

**Pull request merged**
