### PR TITLE
Run partner tests on release

### PR DESCRIPTION
**Pull request by hjdivad**

### CODE REVIEW

**Comment by igorT** [comment]
We run the release branch tests usually after doing point releases. At that point, the partner app might be using newer features, so might fail the tests even if the release branch works. Thats why the beta branch tests are much more useful for new releases.

**Comment by hjdivad** [comment]
> We run the release branch tests usually after doing point releases.

Do you mean manually?

The motivation here is to get partner tests running for PRs that backport fixes before making a point release.

**Comment by igorT** [comment]
@hjdivad I understand the motivation, but the problem is that if the point release is after there has been a newer release the partner app might not be passing anymore

**Comment by hjdivad** [comment]
> @hjdivad I understand the motivation, but the problem is that if the point release is after there has been a newer release the partner app might not be passing anymore

ok.  I'll leave the PR open for now and try to find some time to include a change to the partner test script that skips partners on a newer release than the one being tested.

**Pull request closed without merging**
