### PR TITLE
[BUGFIX release] Transition to loaded.saved state after rollback

### LINKED ISSUE #3499: model.rollbackAttributes with errors doesn't clear hasDirtyAttributes
Steps to reproduce:

1. dirty a model in a way that causes validation errors
2. save
3. rollback
4. model.hasDirtyAttributes == true

If I call model.rollbackAttributes() twice hasDirtyAttributes == false. Also, my models value do appear to be reset.. meaning the changes are reverted but hasDirtyAttributes reflects incorrectly.

DEBUG: -------------------------------
ember.debug.js:5361DEBUG: Ember                          : 1.13.2
ember.debug.js:5361DEBUG: Ember Data                     : 1.13.4
ember.debug.js:5361DEBUG: jQuery                         : 1.11.3
ember.debug.js:5361DEBUG: Ember Simple Auth              : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth Cookie Store : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth OAuth 2.0    : 0.8.0
ember.debug.js:5361DEBUG: -------------------------------

### PR DESCRIPTION
**Pull request by tchak**
Closes #3499 #3498

### CODE REVIEW

**Comment by bmac** [comment]
Looks good to me.

**Comment by tchak** [comment]
In case of #3498 I have added tests that prouves my interpretation of the issue. The behavior is intended.

**Comment by tchak** [comment]
Oops. Fixed.

**Comment by tchak** [comment]
There is probably more to the #3498 then I thought. Working on it.

**Comment by tchak** [comment]
@bmac @fivetanley updated with new fixe for #3498

**Comment by tchak** [comment]
@stefanpenner I replaced usage of `Ember.Enumerable` with `Ember.ArrayProxy` for now. I am not sure what is the future of `Ember.ArrayProxy` but it is used extensively in `ember-data` so I think it is fine for now and I don't want to bother reimplement it in terms of `Ember.Array`.

**Comment by stefanpenner** [comment]
> @stefanpenner I replaced usage of Ember.Enumerable with Ember.ArrayProxy for now. I am not sure what is the future of Ember.ArrayProxy but it is used extensively in ember-data so I think it is fine for now and I don't want to bother reimplement it in terms of Ember.Array.

its staying around for 2.x, after that lets see.

**Pull request merged**
