### PR TITLE
Fix JSDoc issues

### PR DESCRIPTION
**Pull request by Turbo87**
see commits

### CODE REVIEW

**Comment by bmac** [comment]
This looks awesome! Do you mind squashing it down to 1 commit?

**Comment by Turbo87** [comment]
sure, no problem. may I ask why though?

**Comment by bmac** [comment]
Actually looking at these commit messages and the fact that this is mostly doc changes, I'm going to merge it as is. 

By convention, Ember Data usually squashes down most prs to make it easier to git bisect thought the code base (lading on a commit with broken tests makes it hard to determine when a bug was introduced).

**Comment by Turbo87** [comment]
I mostly agree, though often I find it easier to bisect when the commits are smaller and that's why I tend to make only one change per commit. Obviously that only works when there are no failing tests, but then again the tests shouldn't fail in the first place. Thanks for merging!

**Pull request merged**
