### PR TITLE
call super in addon#init

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by fivetanley** [comment]
does this require `[bugfix beta]` or `bugfix release`?

**Comment by stefanpenner** [comment]
It can land as it wants to, ember-cli still supports both and likely will for some time.

The sooner the better, but ultimately no rush.

**Comment by bmac** [comment]
Thanks @stefanpenner.

**Comment by Turbo87** [comment]
Would be cool if this was picked to the `release` branch. Ember CLI stable (v2.6.0) started spitting out warnings about it now.

**Comment by bmac** [comment]
Thanks @Turbo87. I have included this pr in the  https://github.com/emberjs/data/releases/tag/v2.6.1 release.

**Comment by Turbo87** [comment]
@bmac awesome, thanks!

**Pull request merged**
